### ISSUE TITLE
Url box google search suggestion

### ISSUE THREAD

**Issue by eaydin79** [tuyafeng/Via#100]
Url box suggestions coming from history but google instant search suggestion (like chrome) will be useful.
![google](https://user-images.githubusercontent.com/32959323/31864738-8aa15eb4-b76b-11e7-90db-7d570b4d1ebf.png)

**Comment by tuyafeng** [comment]
The search suggestion really needs improvement.

**Comment by Mitia99** [comment]
@tuyafeng Please also add an option to disable google search suggestions in settings when it will be availbale.It will save data.

**Comment by Mitia99** [comment]
@tuyafeng Something like this will be great![Screenshot_20201105_080917_idm.internet.download.manager.plus.jpg](https://user-images.githubusercontent.com/56766778/98200388-8da89080-1f3e-11eb-9eaa-48b435adc3c4.jpg)

**Comment by tuyafeng** [comment]
Search suggestions were introduced in version 4.4.6.
