### ISSUE TITLE
希望网站设定里增加允许混合内容

### ISSUE THREAD

**Issue by xiaokaixuan** [tuyafeng/Via#1004]

**Comment by tuyafeng** [comment]
@xiaokaixuan 现在默认是允许的，提出这个需求是因为碰到了什么问题吗？

**Comment by xiaokaixuan** [comment]
> @xiaokaixuan 现在默认是允许的，提出这个需求是因为碰到了什么问题吗？

内网搭建的AriaNG是http的，在https页面把下载地址推送到AriaNG下载时，一直没成功过，据说Android 5.0以后默认是禁止的。

**Comment by tuyafeng** [comment]
与此无关，我也在局域网搭建了 aria2，用的也是 ariaNG，未出现任何问题。

[AriaNG](https://ibb.co/7rh3BpT)

**Comment by xiaokaixuan** [comment]
OK  找到原因了，谢谢。
