### ISSUE TITLE
Certificate error pop-up

### ISSUE THREAD

**Issue by Mugworth** [tuyafeng/Via#1026]
Whenever im opening less known websites (as less known i mean even duck duck go website!) there is this annoying error warning about the website not being trusted, and asking if i want to proceed anyway, im not sure if this was pointed out here but on play shop, i saw people complaining about the same thing, so i dont think its error on my side.

Anyway if im already at this i would like to add that, Dev you are making awesome work, im not using this browser for long but i already consider it one of the best.
Keep up the great work!

**Comment by tuyafeng** [comment]
thank you for your support. The certificate pop-up may be because you are running software like adguard that implements ad filtering through vpn. If you just want to filter ads, you can do it by subscribing to ad rules, in Settings - General - Ad blocking - Filter subscriptions.
