### ISSUE TITLE
A desperate request

### ISSUE THREAD

**Issue by GoluLiliput** [tuyafeng/Via#1027]
Please please add 'add to homescreen' and 'install webapp' for supported websites like in chrome and mozilla![IMG_20220126_025313.jpg](https://user-images.githubusercontent.com/60719832/151062156-c107bf7a-8a9d-4254-bc3a-c0bfe9413bb4.jpg)... Please please do this. I really don't want to switch my browser app to anything else. I really really love via.

**Comment by liquidhelium** [comment]
you can simply do that by long pressing the "add bookmark" button 👍 

as for "web app", i think it could be a chrome-only feature?

**Comment by liquidhelium** [comment]
anyway, "add to home screen" is useable

**Comment by tuyafeng** [comment]
You can long press the "Add bookmark" button in the menu to add current website to homescreen.
