### ISSUE TITLE
请问via app如何清空书签，导入书签和旧的有重复

### ISSUE THREAD

**Issue by lyjhyjyes** [tuyafeng/Via#1028]
目前打开书签，只能勾选全部根目录的书签，子目录无法全选，只能单独删除，不够方便。
请问如何清空书签，自定义导入html书签

**Comment by linlinzzo** [comment]
卸载。滑稽

**Comment by linlinzzo** [comment]
> > 卸载。滑稽
> 
> 你有毛病吗？不过是正常的提问，重复书签的确是个问题

我的确有毛病，是个傻逼，谢谢您的提醒。

**Comment by tuyafeng** [comment]
实现清空书签在代码上很简单，但我觉得这个选项不足够必要添加到 app 中。

书签本身是浏览器中最重要的数据，提供这样的选项，似乎太过超出管理书签的职责，换种说法，书签被清空和卸载浏览器其实基本上算是一回事。
