### ISSUE TITLE
[Feature request] option to hide the URL.

### ISSUE THREAD

**Issue by Mesum-Hussain** [tuyafeng/Via#1053]
I would like an option somewhere in the settings for hiding the URL bar of the websites. Honestly it will look more minimalistic with that feature. Besides who cares about the URL anyway? Just add a button beside the home button, to copy the URL of the page so that sharing remain convenient. Searching for a page using URL will not be affected as I tried pasting it in the search bar and it works. 

Besides I can't find the source code anywhere. Is this app really open source?

**Comment by tuyafeng** [comment]
You can change the "Toolbar UI mode" to achieve this, just set "Settings" - "General" - "Toolbar UI mode" as "Toolbar at bottom". And you can change the "Auto-hide toolbars" preference to hide the bars while browsing.

**The repository is set for localization and feedback.**
