### ISSUE TITLE
Download an older version.

### ISSUE THREAD

**Issue by changxinjie** [tuyafeng/Via#1074]
I have an older android devices which running Android 2.3,  where  can  I download the appropriate version ?

**Comment by Mesum-Hussain** [comment]
I don't think Via Browser even existed when Android 3 released. Might want to consider getting a newer device or update to a newer version if you can, as you might struggle a lot with every app with that Android version.

**Comment by changxinjie** [comment]
The Version 3.1.3 can work well in my Android 2.3 device. 
Could you upload the APK files to `Releases` every time you release a new version ?

**Comment by tuyafeng** [comment]
android2.3 is too old, and only a small percentage of people are using 2.3 devices, so from a certain version (too long for me to remember), Via stopped supporting android2.3.
