### ISSUE TITLE
大佬，能不能加入URL Scheme支持？

### ISSUE THREAD

**Issue by bluebat1** [tuyafeng/Via#1082]
跳转各种应用

**Comment by bluebat1** [comment]
snssdk1128://webview?url={{url}}&from=webview&refer=web 抖音的这个跳转不了~

**Comment by AyakaAgo** [comment]
可以打开的啊

抖音（20.5.0版本） [snssdk1128://](snssdk1128://)
抖音极速版（20.5.0版本） [snssdk2329://](snssdk2329://)
抖音火山版（13.9.0版本） [snssdk1112://](snssdk1112://)

**Comment by tuyafeng** [comment]
一直支持的。

**Comment by bluebat1** [comment]
哦哦，可能是我的手机问题
