### ISSUE TITLE
无法保存 blob: 大型文件 (Unable to save blob: large file)

### ISSUE THREAD

**Issue by AyakaAgo** [tuyafeng/Via#1087]
在保存一个 200 MB+ *~~小而美~~*文件时提示下载失败 (具体多大才会失败不知道)

这是一个[使用 `blob:` 的测试页面](http://br.furx.top:3000/)

使用 Chrome, Edge 保存正常

----

Download failed when saving 200 MB+ file (don't know how big to fail)

Here's a [test page using `blob:`](http://br.furx.top:3000/)

Saves fine with Chrome, Edge

![下载失败的提示 (download failed toast)](https://user-images.githubusercontent.com/20831549/166135506-a5b492cc-4a84-45a0-8386-be11deb52c11.jpg)

**Comment by tuyafeng** [comment]
是的，这是已知问题，blob 数据超出 100M 后无法保存，后续会修复。

**Comment by tuyafeng** [comment]
最新版本中已经修复了该问题。
