### ISSUE TITLE
google账号泄露

### ISSUE THREAD

**Issue by zhiting9420** [tuyafeng/Via#1091]
登录google账号时要求开启JavaScript，开启之后能正常登录。
之后QQ被挤下去了 俩次。。

**Comment by linlinzzo** [comment]
所以问题是什么？开启 js 很正常啊。

**Comment by zhiting9420** [comment]
不是软件问题就是插件 具体不清楚
![Screenshot_20220508_101838_mark via](https://user-images.githubusercontent.com/53212274/173226678-95e29181-0ad9-4b6d-8541-c6b3fedab675.jpg)
![Screenshot_20220508_101945_mark via](https://user-images.githubusercontent.com/53212274/173226691-8b1315b7-dd2d-46b0-aa82-8fd53f2c2667.jpg)
![Screenshot_20220523_203340_mark via](https://user-images.githubusercontent.com/53212274/173226697-e6e9032f-afe8-46bb-9aaf-16faa731109f.jpg)

**Comment by tuyafeng** [comment]
Google 会限制 WebView 上的登录请求，可以尝试使用其他浏览器标识重试看看。

**Comment by zhiting9420** [comment]
主要是想反应有数据泄露  插件或者是某些原因

**Comment by zhiting9420** [comment]
![via 隐私](https://user-images.githubusercontent.com/53212274/188068634-6a711eab-5c1c-4c7d-b55a-6147d9aa639c.jpg)

这个是什么意思 能解释一下吗？请求 不出售 分享 数据 隐私？ 可以反过来理解吗？  

书签只能保存几十个就不能了 服务器是多大的硬盘啊😯  弄一个webdav功能可以自己保存数据 

 代码没有完全开源
