### ISSUE TITLE
【功能建议】分段/“多线程”下载设置？

### ISSUE THREAD

**Issue by 14725** [tuyafeng/Via#1111]
我下载某网站的文件，但我不希望分段下载。（例如某些网站允许断点续传但不允许“多线程”分段下载，此时我希望把它关闭。）

将来会有设置选项的，对吧？

**Comment by tuyafeng** [comment]
@14725 当网站禁止多线程下载时，Via 也只会使用一个线程去下载它的。而且线程数也不是固定的，同样会因为下载的文件大小和资源属性变化。

**Comment by 14725** [comment]
无论如何，系统下载器的回归是一件好事，这样允许单线程下载。

其实我想能不能只下一半文件，毕竟一些文件只有一半是能用的，并且节省时间（如一堆小文件的压缩包，从中只取一个文件）
