### ISSUE TITLE
【功能建议】增加强制缩放功能

### ISSUE THREAD

**Issue by hatsunevocal** [tuyafeng/Via#1126]
https://mp.weixin.qq.com/s?search_click_id=1535752026550320742-1655437303425-325082&__biz=Mzg2MzczNDgyNQ==&mid=2247491895&idx=3&sn=9819dd1e30fb91e50c96bb09bd13075d&chksm=ce76bc71f90135675db38c813fbbd187b30251aa1508518aa299c7b1bc2fad40f8971be76ef6&scene=0&subscene=10000&clicktime=1655437303&enterid=1655437303&sessionid=0&ascene=65&realreporttime=1655437303447&forceh5=1&devicetype=android-29&version=28001755&nettype=ctnet&abtest_cookie=AAACAA%3D%3D&lang=zh_CN&exportkey=AzaT%2Bmv4NAvNcNi5YbQAQyA%3D&pass_ticket=vGDWnMKOMSP0MuQP4c3RvFumwLyJudWa%2FqPmyMocAMaSOv8XFo8zhGNleugAebyI&wx_header=3
微信公众号的网页大多不支持缩放

**Comment by tuyafeng** [comment]
与 #1041 重复，故关闭。
