### ISSUE TITLE
[Enhancement]不自动清空“页内查找”输入框 (Don't automatically clear "Find in Page" EditText)

### ISSUE THREAD

**Issue by AyakaAgo** [tuyafeng/Via#1134]
![“页内查找”工具栏 ("find in page" toolbar)](https://user-images.githubusercontent.com/20831549/175280576-ee2220b1-51b5-43e8-a021-fe30752d8182.jpg)

有时我们需要在不同页面查找相同的内容，但是“页内查找”输入框会在“页内查找”工具栏关闭后清空。

而切换/新建/关闭标签页、打开菜单、打开网页信息菜单会关闭“页内查找”工具栏。

（其他行为：在同一标签页加载新页面时会自动全选“页内查找”输入框。）

建议不自动清除内容，而是改为在显示时自动全选（或添加一个“清空”按钮）让用户选择是否清空。

--------------------------------------

Sometimes we need to find the same content on different tabs, and the "Find In Page" EditText will be cleared after it's toolbar is closed.

Switching/creating/closing tabs, opening menu, and opening webpage information menu causes the "Find in Page" toolbar to close.

(Other behavior: the "Find in Page" EditText is automatically "select all" when a new page is loaded in the same tab.)

It's better not to automatically clear it, but instead to automatically select all when displayed (or add a "clear" button) to let the user choose whether to clear or modify.

**Comment by tuyafeng** [comment]
该问题已解决。
