### ISSUE TITLE
[Feature Request] Add support for userscripts

### ISSUE THREAD

**Issue by kyoyacchi** [tuyafeng/Via#1136]
I want to use some userscripts instead of that scripts thing. Is it possible?

**Comment by pc00per** [comment]
Technically, you're asking tampermonkey integration.

**Comment by EricDru** [comment]
I'm puzzled. This exists!

In Settings > Scripts
Click '+'
Under "// Your script here"
Type "alert ('Hello');"
Save
Reload a Web page ...

**Comment by kyoyacchi** [comment]
> I want to use some userscripts **instead of that scripts thing**. Is it possible?



> I'm puzzled. This exists!
> 
> In Settings > Scripts Click '+' Under "// Your script here" Type "alert ('Hello');" Save Reload a Web page ...

**Comment by EricDru** [comment]
Oh, do you mean "that scripts thing" is not the same as greasyfork / tampermonkey / grease monkey / violentmonkey integration?

It looks the same to me, just not an extension, but built-in ...

If the script from elsewhere doesn't work, that''s another matter. Java script / ecmascript is pretty standard, and the DOM is presumably same as Chrome, since it is WebView,  no?

**Comment by kyoyacchi** [comment]
> 

No, i meant exactly as them, but doesn't work when i add userscript to it

**Comment by EricDru** [comment]
I believe there are some things that are controlled by Android, not by the browser, unlike a desktop OS that leaves more control to the browser.

'Context menus' are one example ...

Browsers that are trying to support extensions (Kiwi, Yandex) find that to be difficult to overcome.

Unless Via is going to also try to support everything that desktop browser extensions can do, I doubt if the UserScript system will.

**Comment by EricDru** [comment]
Does the script you want to use work in other browsers?

**Comment by tuyafeng** [comment]
User scripts are currently supported.

**Comment by liujianchao1995** [comment]
[> 
#](https://github.com/immersive-translate/immersive-translate/issues/163#issuecomment-1443460675)
