### ISSUE TITLE
自定义浏览器搜索内容填充位置错误

### ISSUE THREAD

**Issue by Megalovaniac** [tuyafeng/Via#1139]
我在自定义浏览器的时候使用
https://global.bing.com/search?q=%s&setmkt=en-US&setlang=en
来在中国大陆使用global bing搜索引擎，可当我输入这个自定义搜索引擎时每次键入内容其都会直接搜索“%s”本身，而我删掉“%s”后也无法为我返回正确的结果。请告诉我该如何正确自定义搜索引擎，在网上查阅的资料并没有帮助，via的自定义搜索引擎实现方式与其他浏览器不同。

**Comment by tuyafeng** [comment]
用这个：
https://global.bing.com/search?setmkt=en-US&setlang=en&q=

Via 是直接把关键词加到链接中，所以需要把 q 参数调到最后。不过在 4.4.0 版本中，对此做了改进，你可以使用 %@ 替换关键词，例如你的例子中，如下链接也是生效的：
https://global.bing.com/search?q=%@&setmkt=en-US&setlang=en
