### ISSUE TITLE
is there any way to open youtube on app?

### ISSUE THREAD

**Issue by Seo2636** [tuyafeng/Via#1156]
I love this browser.

I want to open youtbe app when I clicked yoitube link.

I changed some settings but it only opens on browser.

Can you help me please?

**Comment by tuyafeng** [comment]
Open the youtube link, then long pressing the share button in the menu.

**Comment by Apocalypse612** [comment]
While this workaround is nice, why is the request to do so automatically being rejected? I have seen several other people request this feature as well, and it would be nice to have.
