### ISSUE TITLE
Dark mode without affecting brightness

### ISSUE THREAD

**Issue by tkosamja** [tuyafeng/Via#116]
I think it was asked before but the issue was closed without explanation. Would it be possible to use the dark theme without lowering the brightness?

**Comment by Vv2233Bb** [comment]
LakorTi, don't you know it is passible to change brightness manually? :)

**Comment by GiovanniCarrozza** [comment]
+1

I use my Samsung S9 with "night mode" enabled so the UI elements are almost all dark, but the brightness is still automatically adjusted by the phone. This makes for a pleasant whole dark experience.

**Comment by tuyafeng** [comment]
I am curious. It seems that the dark mode of Samsung devices is different from other devices. This is confusing. Can you provide more information (for example, from which version Samsung started to support dark colors)? I prefer to optimize for Samsung devices.

**Comment by tuyafeng** [comment]
It's already 2021, and this problem has finally been solved.
