### ISSUE TITLE
via浏览器未来会开源吗?

### ISSUE THREAD

**Issue by TwiEmbers** [tuyafeng/Via#1166]
via目前并没有开源，想知道如果可能，via能否开源(非常想学习via的源码)

**Comment by xiaochentianyu** [comment]
并不希望它开源，因为开源之后可能会被奸商利用。但是我希望没人维护它的时候把它开源，让大家一起维护

**Comment by tuyafeng** [comment]
@xiaochentianyu 后续有开源部分组件的计划。完全开源不考虑，不遵守协议的人太多了。

**Comment by xiaochentianyu** [comment]
> 
最近打算写一个导航页，翻看源码发现有暴露via，不知道暴露出的via都有啥功能？还有，就是能不能提供一个请求的事件方便跨域请求？我想给导航页加点小功能。需要一个能跨域请求的办法，还有就是要能拿到收藏的书签和历史记录最好有使用频率。暂定的导航页上显示每日一句[经典语句或者英语，也可以加个左右滑动获取其他信息]，中间搜索框，下面收藏的网址和历史网址[例如看小说，只需要收藏一次就根据历史记录拿到最新的章节不用每次去翻历史找]

**Comment by tuyafeng** [comment]
@xiaochentianyu 我觉得看你的需求。如果你的导航页是本地主页的话，非常不推荐浪费时间去开发，因为现在移动端对文件协议都比较严格，有很多安全问题。如果是正常的网页，更不建议使用 Via 私有的 API。网页应该是适配所有浏览器的，而不是局限于单纯为某个浏览器开发。

**Comment by xiaochentianyu** [comment]
> @xiaochentianyu 我觉得看你的需求。如果你的导航页是本地主页的话，非常不推荐浪费时间去开发，因为现在移动端对文件协议都比较严格，有很多安全问题。如果是正常的网页，更不建议使用 Via 私有的 API。网页应该是适配所有浏览器的，而不是局限于单纯为某个浏览器开发。

单纯自己用的，做个服务器转发就有些浪费了，看来只能找开放平台的一些api来用了。
