### ISSUE TITLE
Dark Mode is broken, not working anymore!

### ISSUE THREAD

**Issue by ShadowMaster85** [tuyafeng/Via#1198]
I have updated Via to the latest version 4.4.3 but now the with the night mode enabled and dark theme for webpages enabled does nothing: all webpages still remains with white background with dark text instead before they are converted to black background with white text as the night mode with dark theme for webpages should do, there is a solution or a fix? I am using a Nokia 2.2 with Android 11. Thanks!

**Comment by igaotang** [comment]
yeah, I have encountered this problem too since updated to the latest version. It went on for a long time.

**Comment by tuyafeng** [comment]
The issue has been fixed.
