### ISSUE TITLE
Accessing the app download link does not redirect to Play Store

### ISSUE THREAD

**Issue by Kita2345** [tuyafeng/Via#1206]
Steps to reproduce
Go to https://m.intl.taobao.com/
Tap on the download app button located at the bottom of the page.
Observe the behaviour.
Expected behaviour
The user is redirected to Play Store.

Actual behaviour
The user is prompted to download the "apk" file.

**Comment by tuyafeng** [comment]
This may be reasonable. Because there are many android application stores in China, and Google Play cannot be accessed, most Chinese companies will distribute apk files on their own servers.
