### ISSUE TITLE
[Bug] 坚果云文件无法下载

### ISSUE THREAD

**Issue by Young-Lord** [tuyafeng/Via#1213]
Via 4.4.4，安卓10，User Agent`Mozilla/5.0 (Linux; Android 10; Mi 6 Build/QQ3A.200805.001;) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36`
在[坚果云](https://www.jianguoyun.com)下载文件时，报错：`下载失败：downloader.HttpException: 416 Requested Range Not Satisfiable`

**Comment by Young-Lord** [comment]
![抓包](https://user-images.githubusercontent.com/51789698/193480421-0a79c8ef-71a8-493b-92df-dc9802806e2b.jpg)
这段抓包是下载一个 5MB 的文件时的所有请求，其中只有最后一个（也就是最上面的一个）带了 Range 请求头，并且出现了 416

**Comment by Young-Lord** [comment]
![系统下载器的抓包](https://user-images.githubusercontent.com/51789698/193480660-68d5fae3-9b61-4657-a13b-b43e8b177cb8.jpg)
作为对比，这是使用系统下载器抓到的数据包，其中最上面的数据包没有发送`Range`头，正常下载

**Comment by tuyafeng** [comment]
收到，我之后看看。

**Comment by tuyafeng** [comment]
很难想象会有下载链接不支持设置 Range 的。我的意思是，不想支持断点续传有更好的做法（比如，不返回 Accept-Ranges 和 Content-Range 头）。但不管怎样，问题已经修复了，想提前体验的话，可以下载测试版：[国内版](https://t.me/ViaAPKs/306)/[Play 版](https://t.me/ViaAPKs/307)。
