### ISSUE TITLE
Search engine localization

### ISSUE THREAD

**Issue by fwlfGH** [tuyafeng/Via#124]
It would be great if the localization affects the Searchengine's language.
So you don't have to use the custom URL Setting only for localization.

**Comment by tuyafeng** [comment]
What search engine uses the wrong language?

**Comment by fwlfGH** [comment]
Hey, it has been quite some time ago. I was using Startpage.
If I select Startpage as search engine it uses English localization.
With custom URL: "https://startpage.com/do/dsearch?cat=web&language=<language>&query="
where <language> could be set to the same as browser language setting.

**Comment by tuyafeng** [comment]
Sorry for my replying so late. I will try to fix it later.

**Comment by tuyafeng** [comment]
Time flies. I noticed that even though the language was different, the search results didn't make any difference. Therefore I will close this issue.

Test links:

- https://startpage.com/do/dsearch?cat=web&language=en&query=测试
- https://startpage.com/do/dsearch?cat=web&language=fr&query=测试
