### ISSUE TITLE
开调试时，发现调试器是黑的。

### ISSUE THREAD

**Issue by pixelvm** [tuyafeng/Via#1246]
![image](https://user-images.githubusercontent.com/888163/203885355-2697cbd0-1745-4000-8873-0904eaed6ec7.png)
这里应该是背景颜色写错了。不过最好是白色背景，将 background 设成 transparent 调试器抓到的仍然是黑色，手机里背景实际是白色。 （小米6; MIUI/11；Android 9; MIUI 经典主题）

**Comment by pixelvm** [comment]
今天切换了黑色系统主题，发现这里也是自动变黑色了，那么这里确实是需要 transparent，或者更好的是根据主题变化来调整 backgroud 的值（这样在调试时，就不总是黑色背景了）。

**Comment by tuyafeng** [comment]
设计如此，为了壁纸功能，所以主页的背景是透明的。暂时没有好的方式实现。
