### ISSUE TITLE
能支持DOH吗

### ISSUE THREAD

**Issue by github0286** [tuyafeng/Via#1271]
众所周知国内dns污染严重,doh能一定程度上解决污染问题

**Comment by BakaJzon** [comment]
via 基于 webview，doh请自行搜索“系统设置＞加密dns/doh”

**Comment by github0286** [comment]
> 众所周知国内dns污染严重,doh能一定程度上解决污染问题

**Comment by BiFangKNT** [comment]
> via 基于 webview，doh请自行搜索“系统设置＞加密dns/doh”

我填了`dot.pub`好像没用啊。我的问题是我有一个家庭服务器，有v6公网，在腾讯云上解析域名，我电脑浏览器可以正常访问，手机上其他浏览器(小米浏览器、chrome、edge)都能正常访问，只有via不行，可是我设了还是返回“net::ERR_NAME_NOT_RESOLVED”，而且此时其他浏览器也不能访问了，只有关闭专用dns才行

**Comment by BiFangKNT** [comment]
顺带一提，我是连家里wifi不行，用流量可以正常上
