### ISSUE TITLE
杀后台后能否保留标签记录以及关于via PAD版的咨询

### ISSUE THREAD

**Issue by qq77522980** [tuyafeng/Via#1273]
作者你好，感谢带来via浏览器这么优秀体验的APP。
我在使用via浏览器过程中有一些想法，惶恐提出，还望考虑采纳：
1、via浏览器在被系统杀后台后，再次打开，之前已经打开的标签全部被清空了，这很不方遍，如果能像edge之类的，再次打开，虽然标签需要重新加载，但是之前的标签都还在；
2、请问android pad版本的via浏览器有在开发么，有进度之类的么，十分希望手机和pad都用via，这样体验就很一致。

**Comment by AyakaAgo** [comment]
1.“设置”-“通用”-“启动时恢复未关闭标签”
总是恢复：启动时自动恢复
优先询问：启动时在底部提示恢复。如果错过提示，仍需手动恢复

2.“设置”-“通用”-“应用布局”
没有分平板/手机端，都可以装，大屏幕上会自动选取为“操作栏在上”，但是还没有像 PC 端浏览器那样的标签栏

![6OV0O85V I 6PX1YMXZ}UG8](https://user-images.githubusercontent.com/20831549/222050957-d579b8fe-5e7e-496e-9fe6-728caddd8345.png)
WSA 上的 Via

**Comment by qq77522980** [comment]
> 1.“设置”-“通用”-“启动时恢复未关闭标签” 总是恢复：启动时自动恢复 优先询问：启动时在底部提示恢复。如果错过提示，仍需手动恢复
> 
> 2.“设置”-“通用”-“应用布局” 没有分平板/手机端，都可以装，大屏幕上会自动选取为“操作栏在上”，但是还没有像 PC 端浏览器那样的标签栏
> 
> ![6OV0O85V I 6PX1YMXZ}UG8](https://user-images.githubusercontent.com/20831549/222050957-d579b8fe-5e7e-496e-9fe6-728caddd8345.png) WSA 上的 Via

第1点完美解决，非常感谢。第2点没有标签的确有点不方便，目前仍然在尝试中。
