### ISSUE TITLE
[Bug] 内建下载速度错误

### ISSUE THREAD

**Issue by BakaJzon** [tuyafeng/Via#1275]
刚开始下载时很正常，一但速度下降后就显示异常了，经常是显示比实际的高
比如显示1.5M/s 实际上是300k-1M间

最离谱的是这个错误数值也会随网络上下浮动。

Via 4.4.7
Harmony OS 2.0.0.7
Huawei Webview 11.1.5 (检测到 Android Webview 88.0.4324.93)

**Comment by tuyafeng** [comment]
下载时手机开启了代理？开启代理后，速度会出错，这目前是已知问题，但无法修复，因为这归根结底是 android 系统流数据计算的问题。

**Comment by BakaJzon** [comment]
emmm，没有开代理。只要是大文件下载都有
