### ISSUE TITLE
无法点击”同意并继续“ android4.4 API19

### ISSUE THREAD

**Issue by WenMoshi** [tuyafeng/Via#1278]
via 4.4.7版本安装到android4.4 API19的电视机和电视盒子上，点击”同意并继续“出现错误代码：play版和chinese版均有此问题。
错误代码：
Exception Happend
Thread[main,5,main]
java.lang ClassNotFoundException: Didn't find class "android.webkit.WebResourceRequest" on path: DexPathList[[zip file"/data/app/mark.via-1.apk"],nativeLibraryDirectories=[/data/app-lib/mark.via-1,/vendor/lib,/system/lib]]
看能否修复。
最后能在android4.4 API19的电视机和电视盒子上用的是via 4.0.7版本，想跟进via新版继续使用新特性。

**Comment by tuyafeng** [comment]
无法在 android4.4 的虚拟机上复现该问题。另外，错误日志提示的 `android.webkit.WebResourceRequest` 在 android4.4 上应该是可用的，目前无法确认具体原因。

**Comment by WenMoshi** [comment]
好的，谢谢大佬。
