### ISSUE TITLE
如何设置可以使得某个网站禁止外连接，或者跳转到到外连接？？

### ISSUE THREAD

**Issue by jianliulin** [tuyafeng/Via#1296]
如何设置可以使得某个网站禁止外连接，或者跳转到到外连接，比如：

当访问   abc.com ，就只看看到abc.com网站的上内内容，也禁止跳转到除了abc.com之外的任何网址，广告太多了，尤其是看小说的时候。

**Comment by tuyafeng** [comment]
你可以尝试直接禁止该网站的 JavaScript（打开该网站 - 点击地址栏左侧盾牌 - 选择网站设定，之后启用并将 JavaScript 设置为禁用）
