### ISSUE TITLE
"启用javascript"这个选项能否移到工具箱里面

### ISSUE THREAD

**Issue by jianliulin** [tuyafeng/Via#1302]
"启用javascript"这个选项能否移到工具箱里面，用的频率还是蛮高的，只要不启用，广告基本就消失了，但有些网站又必须启用，所以希望能方便的来回切换，

**Comment by tuyafeng** [comment]
你好，建议你直接为指定网站禁用 JavaScript，你可以打开那个网站，点击地址栏左侧盾牌按钮，选择网站设定，在设定里关闭 JavaScript 就好。
