### ISSUE TITLE
Feature Request - Disable video player

### ISSUE THREAD

**Issue by risky777** [tuyafeng/Via#1303]
Hi

When I'm at home, I would like to use Via as web-interface to my enigma2 (linux-based) satellite-tv-receiver. Problem is that for media-links Via opens built-in video-player which doesn't play ts-streams, this leads to many clicks to open mpv or vlc. Could you add option to disable built-in video-player and redirect media-link to external-player like mpv or vlc?

**Comment by tuyafeng** [comment]
In the latest version, you can choose your preferred video player in “Settings - General - External video player” :)

**Comment by risky777** [comment]
1. This setting-redirection does nothing, stream goes to internal player instead of external-selected (vlc or mpv).
- additional-info:
    - here's typical enigma2 stream url
        http://192.168.255.166/web/stream.m3u?ref=1%3A0%3A1%3A331%3A194E%3A194E%3A2080000%3A0%3A0%3A0%3A&name=AVA+Family&fname=AVA+Family&device=etc
    - stream is ts (transport-stream) h264-aac

2. Is it possible to add buttons to Via toolbar? In Opera I added "Share" button to toolbar, this way I can quickly share link to external app (vlc or mpv) without long-click...
