### ISSUE TITLE
关于泛域名证书

### ISSUE THREAD

**Issue by ZIDOUZI** [tuyafeng/Via#1309]
via浏览器貌似不支持泛域名证书？如果是，是否有这方面的打算；如果已经支持，应该如何启用？

**Comment by ghidgdsr** [comment]
好像支持的吧，我就没问题

**Comment by ZIDOUZI** [comment]
> 好像支持的吧，我就没问题

我用acme创建的泛域名证书在edge上能正常访问, 但用via就提示域名与证书不匹配了

**Comment by ghidgdsr** [comment]
Try again later!

**Comment by tuyafeng** [comment]
我觉得最好先确认你的证书是否正确配置比较好，你可以使用 Chrome 看看问题是否还存在。

**Comment by ghidgdsr** [comment]
Try again later!

**Comment by ZIDOUZI** [comment]
> 我觉得最好先确认你的证书是否正确配置比较好，你可以使用 Chrome 看看问题是否还存在。

同为chromium的edge没有问题, 我在上面就提到过了

**Comment by tuyafeng** [comment]
你可以用 Via 打开 viayoo.com，我为这个网站配置的也是个泛域名的证书（打开这个网站 - 点击地址栏左侧盾牌 - 选择查看证书），没有错误提示的。用同样的方式查看你的网站对应的证书，看看公用名 CN 是否正确，我倾向是证书的配置问题。如果你确认证书配置正确，也可以在这里贴出你的网站，我可以帮你看看。

**Comment by ZIDOUZI** [comment]
刚刚又测试了一下. 
最开始发现这个问题是使用光速虚拟机的时候, 访问我搭建的云盘提示证书警告. 更新后也会警告.
但是刚刚在真机内安装via之后没有提示证书警告. 
虚拟机内访问via官网也没有警告.
