### ISSUE TITLE
[Feature Request] Allow the users to add Chrome Extensions.

### ISSUE THREAD

**Issue by Mesum-Hussain** [tuyafeng/Via#1318]
Via is my favourite mobile browser, but the only thing holding me back from using it as my primary mobile browser is that I can't use some Chrome Extensions which are very important to my workflow.
Please allow the users to add Chrome Extensions to the Via browser.

**Comment by ulist** [comment]
Yes chrome extensions when

**Comment by Lucas04-nhr** [comment]
It can add user scripts in setting, but the scripts I add may not work functionally.

**Comment by tuyafeng** [comment]
I am not planning to implement this feature in the near future, as I have other more urgent tasks to focus on right now.
