### ISSUE TITLE
后台播放问题

### ISSUE THREAD

**Issue by Link000666** [tuyafeng/Via#1323]
大佬有没有考虑加入类似于Chrome或者Firefox在安卓端上的视频后台播放功能，或者像夸克那样视频以音频形式播放的功能；

**Comment by naloder** [comment]
webview自身限制无法做到

**Comment by Link000666** [comment]
> webview自身限制无法做到

 额，原谅我本身没什么技术，但是我在网上搜索webview开发的时候发现是可以解决这个问题的，通过扩展WebView并覆盖onWindowVisibilityChanged；参考https://it.cha138.com/javascript/show-72749.html

**Comment by tuyafeng** [comment]
考虑到 webview 非常耗电，暂时没有开发后台播放功能的计划。
