### ISSUE TITLE
ERC-4804 support: Add support for translation of EVM call messages from Web3 URLs

### ISSUE THREAD

**Issue by KingKratus** [tuyafeng/Via#1328]
We would like to request that the open source Via Browser add support for translating Web3 URLs to EVM call messages according to the ERC-4804 standard.

Currently, reading Web3 data relies mainly on a translation performed by a Web2 proxy for Web3://. The translation is mainly performed by the proxies, such as dApp sites, node/etherscan service providers, which are out of the users' control. The ERC-4804 standard aims to provide a simple way for Web2 users to directly access Web3 content, especially content on the chain, such as SVG/HTML.

Support for the ERC-4804 standard will allow users to easily access Web3 content while enabling interoperability with other standards that already support URIs such as SVG/HTML.

Please consider adding support for the ERC-4804 standard to Via Browser to allow users to easily access Web3 content directly, without relying on Web2 proxies.

Thank you for your time and consideration.

**Comment by tuyafeng** [comment]
Please check [scoute-dich/browser](https://github.com/scoute-dich/browser).
