### ISSUE TITLE
[ISSUE] Cloudflare Captcha

### ISSUE THREAD

**Issue by qxb3** [tuyafeng/Via#1329]
Hello! there is some weird issue arround regarding cloudflare captcha. when accessing a website that has cloudflare captcha enabled (like chatgpt) sometimes it doesnt work when i completed the verification if i am a human. it just redirected me to the same verification page. this behavior doesnt work on any browser, just this browser via.

**Comment by tuyafeng** [comment]
Setting User-Agent to default should fix this.
