### ISSUE TITLE
Ability to create a list of blocked sites

### ISSUE THREAD

**Issue by x9136** [tuyafeng/Via#1331]
Hello!

A list of blocked sites is a way to control your time on the Internet. People develop habits for visiting entertainment sites and without the list it's harder to do otherwise.

It would be useful to have a build-in feature to block sites. Simple one, like https://github.com/penge/block-site for example. Maybe with a redirect feature.

What do you think?

**Comment by qxb3** [comment]
You could make a script that redirects to somewhere if the current website you are accessing is ones that you blocks

**Comment by x9136** [comment]
@qxb3 You're right, but I need to learn how to write scripts. I found one script and I'll figure out how to redo it for myself. Though it's better when the blocking or redirecting feature is in the interface.

**Comment by qxb3** [comment]
i agree. learning a whole new difficult skill just to block some website isn't really reasonable. i actually currently making a website where one can find and share scripts. there is this one: https://greasyfork.org/en which this browser scripts is based out of. check it out and maybe u can find what you looking for.

**Comment by x9136** [comment]
I tried different versions of the script, this one worked for me.
```
// ==UserScript==
// @name Redirect
// @namespace Redirect
// @version 0.1
// @description Redirect
// @author You
// @include https://url1toredirect.net/*
// @include https://url2toredirect.net/*
// @grant none
// ==/UserScript==

window.location.assign("https://urlwheretogo.com");
```
