### ISSUE TITLE
VIA on android 4.3

### ISSUE THREAD

**Issue by darkalexis1990** [tuyafeng/Via#1334]
how to improve web experience on android 4.3 with via? i mean what other should i download? cause a lot of sites like yt or fb is does not loading.

thanks.

**Comment by heartlog** [comment]
Use their alternative frontends...

**Comment by darkalexis1990** [comment]
which are?

**Comment by heartlog** [comment]
You can refer [this repo](https://github.com/digitalblossom/alternative-frontends) to get alternative frontends of websites like YouTube, Twitter, reddit and ..
