### ISSUE TITLE
[Feature Request] Add OCR And wsrv.nl Service

### ISSUE THREAD

**Issue by julptk** [tuyafeng/Via#1335]
if posible, that good for reading comics

**Comment by 3ekodomo** [comment]
> if posible, that good for reading comics

Well, I understand man !!
wsrv not always work it stops with cdn based images sometimes. But you can use other method to improve manga reading.
I found a script that screenshot the website and send us full screenshot of webpage, saving data. [Check here](https://github.com/heartlog/Userscript/ScreenshotASite)
