### ISSUE TITLE
Block Youtube ads

### ISSUE THREAD

**Issue by AayushBoliya** [tuyafeng/Via#1344]
Is there any way to block youtube ads through scripts in Via browser?

**Comment by DesolateIntention** [comment]
i second this

**Comment by tuyafeng** [comment]
This issue does not match the topic, I will close it, please report the issue of the browser itself.

**Comment by heartlog** [comment]
@AayushBoliya
You can't block YouTube ads,but can watch YouTube video in YouTube alternative frontend.
