### ISSUE TITLE
[Favourite Icons] Some ideas

### ISSUE THREAD

**Issue by Dan-TBA** [tuyafeng/Via#1350]
![Untitled9_20230520200013](https://github.com/tuyafeng/Via/assets/82999543/409f4871-9087-4a02-8802-3f28fbdb9278)

Also, may I ask: What is CSS in Customization tab in Via Browser?

**Comment by tuyafeng** [comment]
The icon depends on the apple touch icon set by the website, and some websites may not be set. You can get a more consistent interface by turning off icon (Customization - Advanced - Icon style).
