### ISSUE TITLE
无法访问GitHub网站

### ISSUE THREAD

**Issue by 3367282243** [tuyafeng/Via#1371]
在使用via浏览器访问GitHub时，4.7.0版本的via还行，4.8.0版本有时直接不加载，有时刷新不出来，直接停在原网页，访问via的协助翻译时更多时候是空白页面，等大半天才显示无法访问

**Comment by Hakuin123** [comment]
我也有这种现象…对有的时候从其他软件跳转到用via打开链接，会等好久才会加载甚至不加载

有的时候网页内点开一个新建标签页的链接也会不加载

地址栏点开是空的
