### ISSUE TITLE
书签导入/同步异常

### ISSUE THREAD

**Issue by wentlwr** [tuyafeng/Via#1424]
导出pc浏览器中water fox浏览器（火狐变种）以及edge浏览器为html格式文件，在via中导入，均出现异常，原书签为多层文件夹嵌套，书签都在“书签工具栏”中储存，如图：
![图片](https://github.com/tuyafeng/Via/assets/81084625/1da33d4d-6726-42e1-aa8e-44dfbe674846)
导入后书签如图
![图片](https://github.com/tuyafeng/Via/assets/81084625/a192a50c-3a85-4931-b144-4137b517a2af)
点开“书签工具栏”文件夹，里面啥东西都没有。但是把该书签文件在其他浏览器中导入是正常的。
使用webdav的方式同步也是一样的效果，书签并没有被导入，请大佬修复下

**Comment by yestoday2009** [comment]
@wentlwr 我也遇到类似的问题 ，请问是怎么解决的呢？

**Comment by 3367282243** [comment]
via浏览器自己的微信公众号上有比较详尽的更新说明，好像有提到过在哪个版本之后使用zip格式导出/备份书签，现在又改回html格式了。via自己的书签导出后的正文内容和其他浏览器的好像有点不一样，具体哪里不一样我看不懂，讲不出来

**Comment by 3367282243** [comment]
作者大大贴心地为大家整理了一下安卓的常见问题见链接：https://viayoo.com/zh-cn/docs/via-for-android-faq.html
下面是截屏
![Screenshot_2024-07-24-19-31-44-20](https://github.com/user-attachments/assets/5f1e0e7e-d5d5-471d-832c-af2ea8ff69c9)
