### ISSUE TITLE
定制菜单建议

### ISSUE THREAD

**Issue by ACodeHX** [tuyafeng/Via#1479]
定制菜单建议添加搜索引擎的选项，可以快速切换搜索引擎，不用进入设置来改

**Comment by RickyZhu-420** [comment]
如果想快速切换搜索引擎，直接点击搜索框的放大镜图标就可以选择切换了。这个功能在早先的版本中已经引入了
![Screenshot_20240304_162828](https://github.com/tuyafeng/Via/assets/137372858/0b65a734-66fd-4968-a10b-e6c0e930ca72)

**Comment by ACodeHX** [comment]
功能隐藏太深看不到，多谢大佬
