### ISSUE TITLE
cn 版 与 gl 版 差异在哪呢？

### ISSUE THREAD

**Issue by AAABingBing** [tuyafeng/Via#1488]
cn 版 与 gl 版 差异在哪呢？

**Comment by KEVIN-G386** [comment]
也许可以参考https://viayoo.com/zh-cn/docs/via-for-android-faq.html#orgfac648b。语言支持不同。国内版本只支持简体中文、繁体中文、英语三种语言，而国际版除以上三种语言外，还支持包括阿拉伯语、法语、西班牙语、日语在内的多种语言。这也是国内版和国际版安装包大小不同的主要原因。
两者的包名不同。你可以在手机上同时安装国内渠道和海外渠道的版本，两个版本不会冲突，都可以正常使用，互不影响。

**Comment by AAABingBing** [comment]
感谢解答
