### ISSUE TITLE
Bookmarks And Folders Icon On The Home Page

### ISSUE THREAD

**Issue by HatoGreyrat** [tuyafeng/Via#1669]
I would like an icon for the bookmarks without images and the folders that are placed on the home page instead of just letters, which looks bad, you could use the ones that can already be seen by accessing the bookmarks

**Comment by mcdz** [comment]
You can just rename logo to text, call it bookmark, or use the 🔖 bookmark emoji and set font size to a bigger value.

Also, did you know, you can access bookmarks/history/saved pages by tapping the via logo or whatever you have on top of home shortcuts, above the search box obviously. :)

**Comment by mcdz** [comment]
Also, you can long press home icon to open bookmarks.
I'm not sure it's set to that by default, but yeah, you can also select what long pressing does on buttons.

**Comment by HatoGreyrat** [comment]
> You can just rename logo to text, call it bookmark, or use the 🔖 bookmark emoji and set font size to a bigger value.
> 
> Also, did you know, you can access bookmarks/history/saved pages by tapping the via logo or whatever you have on top of home shortcuts, above the search box obviously. :)

I hadn't noticed that clicking on the logo would take you to your bookmarks XD Thanks, but anyway, I'd like to add shortcuts to my home page and have the icons be the original ones from the websites or at least have a star icon instead of just a letter and a folder icon for the folders because in dark mode the icons that are a letter with a different colored background don't look very good.
