### ISSUE TITLE
Keyboard overlaps text input

### ISSUE THREAD

**Issue by UDPSendToFailed** [tuyafeng/Via#206]
Hi! I want to say thanks for this great browser, working perfectly on low RAM devices too. But it has a problem:

Android soft keyboard overlaps the text input fields, and there is no way to scroll down and see what I'm typing. The only solution is closing the keyboard to see the text.  This makes text input so annoying on websites where the text box is on the bottom of page.

**Comment by tuyafeng** [comment]
This is indeed a problem, but I still have not found the best solution, and `adjustResize` has been defined in manifest, but as you can see, the effect is still not good, I will keep this issue open until I find the best solution.

**Comment by tuyafeng** [comment]
It's already 2021, and this problem has finally been solved in version 4.3.2.
