### ISSUE TITLE
无法拍照然后上传图片

### ISSUE THREAD

**Issue by chrvip** [tuyafeng/Via#218]
我通过一个
<input type="file" accept="image/jpg,image/png,image/jpeg,image/gif" capture="camera" @change="onFileChange"
               style="display: none;"> 
来拍照并上传，不显示照相图标，从而拍照并上传，而系统自带浏览器可以的。
手机：小米6 MIUI 10
e-mail: chrvip@outlook.com

**Comment by tuyafeng** [comment]
当前上传确实存在问题，这个我看看能否解决。

**Comment by tuyafeng** [comment]
鉴于这个 issue 和 issue #422 类似，我决定关闭这个来保持 issue 列表的单一性。
