### ISSUE TITLE
Scripts not working 

### ISSUE THREAD

**Issue by ImranNayan** [tuyafeng/Via#288]
I add a java script

Domain: *
var sheet = document.createElement('style') sheet.innerHTML = "div {border: 2px solid black; background-color: blue;}"; document.body.appendChild(sheet);

But it not affect any web page at all.

**Comment by Hardisulaeman** [comment]
Saya setuju pendapat anda 👍💖

**Comment by ImranNayan** [comment]
I can't understand what are you talking about. Please English only.

**Comment by ImranNayan** [comment]
So plz tell me what type of script it support. May I use such a plain Java scrip? So why its not working?

**Comment by ImranNayan** [comment]
Even TEXT link to Clickable Hyperlink add on not working

**Comment by tuyafeng** [comment]
It may be covered by the style of the website?

**Comment by qwerrjk** [comment]
🤓
