### ISSUE TITLE
Source code of app

### ISSUE THREAD

**Issue by ChronosX88** [tuyafeng/Via#336]
Where is the source of this browser? I would like to see them. I have to make sure that there are no tracking components in this browser.

**Comment by holykol** [comment]
See https://reports.exodus-privacy.eu.org/en/reports/65699/
From this report Via uses Flurry analytics. This could be **potentially** used for tracking users.

**Comment by GodApollon** [comment]
In my opinion Via is closed source probably because the Dev wants to hide the code not to be "stolen"..... by those dangerous copy paste code "Devs"..... If this was released 
probably Next day you would see in Play Store "Sia Browser" ... "Xia Browser", and do on........ if you know what I mean.

**Comment by Raul1198** [comment]
Agreed , Exodus show  tracker !!

**Comment by vitaly-zdanevich** [comment]
Hmmm, I want to use free and open source software.

**Comment by pc00per** [comment]
Searched for this. Looks like he'll never open it.
