### ISSUE TITLE
Suggestion: Built-in uploader.

### ISSUE THREAD

**Issue by pthfdr-42** [tuyafeng/Via#341]
If Chrome is uninstalled (e.g. using "pure" WebView), the uploader is broken. Any uploads will result in a "No apps can perform this action" error.

**Comment by tuyafeng** [comment]
Are you sure? Did you delete the system's "Document" app?

**Comment by pthfdr-42** [comment]
@tuyafeng No. I tried the LineageOS with all system apps intact and this still happens.

**Comment by tuyafeng** [comment]
Well, I will check again later.

**Comment by tuyafeng** [comment]
This problem does exist. Because this issue is similar to an issue #422 , I will close this to keep the issue list single.
