### ISSUE TITLE
Inverted colors mode

### ISSUE THREAD

**Issue by ujos** [tuyafeng/Via#361]
Could you please add inverted colors mode. It will be good addition to the night mode. 

The point of inverted mode is that not just text color is inverted but images also. For example, on Wiki there are gif/png images with black text and transparent background. If page background is inverted to black and images are not inverted, then black-on-transparent images are not readable.

**Comment by ujos** [comment]
Following is another browser, which supports this feature. Unfortunatelly it is not available on the Google Play anymore.

https://apkpure.com/black-white-browser/kuribohstudio.app.blackandwhitebrowser

**Comment by ujos** [comment]
I've found Inverted Colors Mode in the Via Browser by long taping on Night Mode button. Issue with images inversion is still actual. Please see screenshot below, formula in the Inverted Mode is not readable as background is black and text of formula is also black.

![via_night_mode](https://user-images.githubusercontent.com/70940/60381429-195e0300-9a55-11e9-9ede-e8de8f9b6bdb.jpg)

**Comment by tuyafeng** [comment]
Inverting the color will cause the images on some web pages to be very strange, which is more unacceptable than the benefits it brings. For this reason, I removed this feature (it did exist before). In the upcoming version(3.9.9), forcedark will be enabled on android10 + devices, which is a more elegant implementation.

**Comment by ujos** [comment]
Well... I used your browser because of this feature and I do not have Android 10 device :)

**Comment by tuyafeng** [comment]
long click the night mode button in menu, this will enable an experimental feature to enabled dark page.
