### ISSUE TITLE
没有应用可执行此操作

### ISSUE THREAD

**Issue by ShangJixin** [tuyafeng/Via#369]
![Screenshot_20190531_225137.jpg](https://i.loli.net/2019/05/31/5cf140d14216528456.jpg)
上传图片时，显示
没有应用可执行此操作
可能与下文有关
https://blog.csdn.net/cdnight/article/details/46985025
求解决方案

**Comment by tuyafeng** [comment]
是什么网站？方便留下设备信息吗？我这边测试上传文件都可以正常使用。

**Comment by tuyafeng** [comment]
经测试确实存在此问题，因为此 issue 与 issue #422 相似，故将关闭这个以保持 issue 列表的单一性。
