### ISSUE TITLE
Can not upload images (and probably other files)

### ISSUE THREAD

**Issue by AndhikaWB** [tuyafeng/Via#374]
Via will always says that there are "No apps can perform this action" although there are some apps that can handle this action. Example of affected site: github.com. I'm currently using Android 9.0.

**Comment by tuyafeng** [comment]
Did you delete the system's "Documentation" application?

**Comment by AndhikaWB** [comment]
No, I know it's a crucial app for the system. I'm using LineageOS 17.1 (based on Android 10).

**Comment by tuyafeng** [comment]
Ok i will check it again.

**Comment by tuyafeng** [comment]
This issue is similar to issue #422 , I will close this one.
