### ISSUE TITLE
点击链接新建的标签页总是在标签列表最后导致用户体验差的问题

### ISSUE THREAD

**Issue by zwz** [tuyafeng/Via#387]
希望点击页面中的链接新建的标签页的次序能够直接在原页面之后
这样关闭这个新建的标签页时，就可以回到原先的页面
而且在标签页列表中也可以让新建的标签页与原页面比较接近，容易查找和切换

如果可以支持用户拖动标签页自定义次序的话，那就更完美了

**Comment by OpenWaygate** [comment]
我也有这个问题，有一个非常不方便的现象
```
Tab 正在浏览的             tab1
Tab 已打开的               tab2
Tab tab1中弹出的广告       tab3
```
正在浏览tab1，弹出一个广告后到了tab3，在tab3点击返回后就到了tab2，这就导致需要手动切换到tab1

**Comment by LakorTi** [comment]
收到，我后续会看看这块。

**Comment by zwz** [comment]
自从你关闭后我已经最新了两个版本了
但是发现所说的这个问题还是没有解决哦

**Comment by tuyafeng** [comment]
暂时开启这个 issue，直到问题解决。

目前 Via 的标签实现是简单的添加到末尾，在不变更当前框架的情况下改动比较困难，所以短时期内可能还会存在很长一段时间。但是目前已经在积极地重构框架。

**Comment by zwz** [comment]
好的，期待更好的via

**Comment by tuyafeng** [comment]
在 4.0.0 版本中，重构了标签部分的操作逻辑，目前已经是根据情况动态在相应位置新建。
