### ISSUE TITLE
Not compatible with Apple developer page

### ISSUE THREAD

**Issue by smekkley** [tuyafeng/Via#427]
https://developer.apple.com/library/archive/documentation/DeviceDrivers/Conceptual/USBBook/USBOverview/USBOverview.html#//apple_ref/doc/uid/TP40002644-TPXREF102

It's not possible to view any content hidden there by JavaScript

**Comment by tuyafeng** [comment]
This is indeed a bug, I will try to solve it.

**Comment by tuyafeng** [comment]
It may take a few days to wait for the update, you can turn off "Go back without Reloading"(Settings - Advanced) to browse this page normally.

**Comment by tuyafeng** [comment]
I will close this issue because I opened an issue for collecting incompatible websites like this.

**Comment by tuyafeng** [comment]
This looks like a generic error. I just opened this link on chrome and the website appears abnormal.
