### ISSUE TITLE
希望能添加对密码管理软件的支持

### ISSUE THREAD

**Issue by Aquaakuma** [tuyafeng/Via#449]
使用密码管理软件，比如Bitwarden，自动填充密码会获取不到网站的域名，我询问了开发者，他说：
In Parser.cs/Parser.SetPackageAndDomain property node.WebDomain is always null or whitespace for each node, therefore Website doesn't get set and Uri getter in the end returns the androidapp://packageName.

大概就是这样。

**Comment by LakorTi** [comment]
是的，这是个玄学问题。我刚刚在手机上测试了，play 版本默认就支持密码填充（包括网站填充），而默认版本不支持网页密码，代码上并未存在任何不同，play 版本也没有对密码填充做过任何优化，我现在也很纳闷。

**Comment by TUT123456** [comment]
加油。。。我就是play版本，填写密码的时候只能填写账号，密码填不上去。也不懂怎么收集错误。。。

**Comment by LakorTi** [comment]
方便说说是什么网站吗？我简单测试了下，play 版本的话填充账号密码没问题诶。

**Comment by TUT123456** [comment]
> 方便说说是什么网站吗？我简单测试了下，play 版本的话填充账号密码没问题诶。

play版现在填充可以了，但是点击转到密码库，密码管理应用显示的是mark.via.gp，只能手动搜索密码在填入了，多了一步工作。

**Comment by TUT123456** [comment]
> > 方便说说是什么网站吗？我简单测试了下，play 版本的话填充账号密码没问题诶。
> 
> play版现在填充可以了，但是点击转到密码库，密码管理应用显示的是mark.via.gp，只能手动搜索密码在填入了，多了一步工作。

github，via play版，bitwarden

**Comment by tuyafeng** [comment]
好的吧，我用内测版本测试了下检测网站没问题，等下个版本（3.9.9）更新了之后再试试看吧。

**Comment by tuyafeng** [comment]
该问题似乎已经解决了。如果依旧碰到问题，可以重新打开该 issue。

**Comment by MimuTao** [comment]
该问题依然出现在了miui14上
