### ISSUE TITLE
在部分网站上图片保存失败的问题

### ISSUE THREAD

**Issue by Cook21** [tuyafeng/Via#470]
- 复现方法：

> https://www.pixiv.net/artworks/60095408

在登陆pixiv账号的状态下，长按图片并选择保存图片，提示下载成功，但查看下载列表发现实际下载失败

- 可能原因：
Via没有给下载器传递相应的Cookie，当提取出的下载链接要求身份认证时，下载就会失败

**Comment by tuyafeng** [comment]
是使用第三方下载器吗？

**Comment by Cook21** [comment]
> 是使用第三方下载器吗？

使用的是系统下载器，系统是华为EMUI10

**Comment by niefy** [comment]
建议优化图片保存功能，正常保存网页图片是可以直接从网页保存到系统磁盘的，VIA为什么需要再次下载？

**Comment by niefy** [comment]
> 建议优化图片保存功能，正常保存网页图片是可以直接从网页保存到系统磁盘的，VIA为什么需要再次下载？

顶我上去

**Comment by tuyafeng** [comment]
@niefy 并不是的，网页缓存的图片分辨率比较小，不够清晰。同时，因为 webview 各版本的差异，操作缓存并不稳定。

**Comment by Cook21** [comment]
@tuyafeng 现在我保存图片的流程是这样的：先把网页离线，然后到Downloads文件夹里找对应的.mht文件，用mht查看器打开然后提取其中的图片资源。从用户的角度来说还是希望能够多一个选择，不然这样太不方便了。

**Comment by Cook21** [comment]
更新：最新4.0.1版长按图片选择查看图片会403，触发条件与开头相同

**Comment by bot74** [comment]
补充：最新4.2.6(20210331)版本此bug依旧存在，系统为EMUI9.1.0，不是第三方下载器

**Comment by bot74** [comment]
> 
> 
> 补充：最新4.2.6(20210331)版本此bug依旧存在，系统为EMUI9.1.0，不是第三方下载器

Phone: HONOR COL-TL10(COL-TL10)
App Version: 4.2.6(20210331)
Snapshot Time: 2021-04-06 12:06:26
CPU ABI: arm64-v8a 
Screen: 1460x720
Android Version: 9 API28
Language: zh-CN
WebView Impl: com.google.android.webview
WebView Version: 74.0.3729.157(372915750)

提供一些Debug信息，希望能有帮助

**Comment by tuyafeng** [comment]
4.2.8 版本情况依旧吗？4.2.8 优化了下载的部分。

**Comment by Cook21** [comment]
已经修复了，感谢
