### ISSUE TITLE
Share link popup menu item

### ISSUE THREAD

**Issue by ujos** [tuyafeng/Via#472]
Please add Share link command to the popup menu appeared while making a long tap on the link on the web page.

**Comment by tuyafeng** [comment]
Is this necessary?

**Comment by ujos** [comment]
My use case is as following:

1. I have Kodi media center installed on Raspberry-PI in my home network
2. I have Yatse app (Kodi remote) installed on the Android phone
3. On the Android phone in the "Share with" window I have a "Play on Kodi" command added by Yatse
4. I start Via browser, open Youtube and in the search box I type some text
5. Youtube returns list of videos.
6. Now I'd like to play some videos in the list. 

So I'd like to be able to make long tap on video in the list and click "Share with" then select "Play on Kodi".

The alternative is to make regular click, load youtube page, stop playback (as video automatically starts playback) then click Tools => Share menu item. 

Later to play another video in the list I need to go back, click on another video, stop playback then click Tools => Share menu item

**Comment by tuyafeng** [comment]
Got it.

**Comment by tuyafeng** [comment]
In the latest version(3.9.10), I have added this feature, you can see it after the update.
