### ISSUE TITLE
请求将长按页面详情加回来

### ISSUE THREAD

**Issue by w311ang** [tuyafeng/Via#474]
想看网址里一参数，在地址栏划着看极其不方便，能长按一链接将网址的全文展示可比地址栏一点点划方便多了

**Comment by w311ang** [comment]
本人非常需要，辛苦了

**Comment by tuyafeng** [comment]
长按菜单的条目实在是太多了，目前暂时不考虑在长按菜单里加入这个功能了。
但是，我想了想，决定使用长按标签条目来展示页面详情，就当作预览来看吧，在之后的版本会添加。

**Comment by w311ang** [comment]
> 长按菜单的条目实在是太多了，目前暂时不考虑在长按菜单里加入这个功能了。
> 但是，我想了想，决定使用长按标签条目来展示页面详情，就当作预览来看吧，在之后的版本会添加。

可行啊，谢谢告知
