### ISSUE TITLE
I have a problem after closing a tab

### ISSUE THREAD

**Issue by N74NK** [tuyafeng/Via#477]
After I did an update on PlayStore, I got a problem.
When I try to close 1 tab, my browser suddenly exits.
Please fix this problem, thanks

**Comment by tuyafeng** [comment]
Does this issue occur every time when closing the tab? Can you tell me the model of your phone?

**Comment by N74NK** [comment]
> Does this issue occur every time when closing the tab? Can you tell me the model of your phone?

My phone is Samsung J3

**Comment by tuyafeng** [comment]
Got it. I will fix it in the next version.
