### ISSUE TITLE
关于增强脚本功能的建议

### ISSUE THREAD

**Issue by URenko** [tuyafeng/Via#480]
现在Via的脚本功能比较简单，虽然大多数XX猴的API都可以通过其他方式来实现，但是有些API，如用于跨域请求的[GM_xmlhttpRequest](https://violentmonkey.github.io/api/gm/#gm_xmlhttprequest)无法单纯通过用户脚本实现，希望能添加类似API

**Comment by tuyafeng** [comment]
受制于 webview 孱弱的接口，脚本能提供的作用实际很有限，如果方便的话可以讲讲跨域的需求，可能有除了脚本之外的更好的解决方案。

**Comment by URenko** [comment]
比如翻译这种需要使用别的网站的服务的

修改响应头可能是一种解决方法：https://stackoverflow.com/questions/17272612/android-webview-disable-cors

**Comment by tuyafeng** [comment]
> 比如翻译这种需要使用别的网站的服务的
> 
> 修改响应头可能是一种解决方法：https://stackoverflow.com/questions/17272612/android-webview-disable-cors

最新版本直接替换了默认的翻译服务，现在的服务提供方是彩云小译，效果还可以。修改头请求不是做不到，但是我觉得这是一种十分不优雅且不可靠的做法，收益颇微而风险巨大。

**Comment by WuJunkai2004** [comment]
> 比如翻译这种需要使用别的网站的服务的
> 
> 修改响应头可能是一种解决方法：https://stackoverflow.com/questions/17272612/android-webview-disable-cors

也许你能找到一些网站，本身就运行跨域请求。或者也可以尝试自建代理服务器。
但是如果允许脚本从互联网上随意访问，可能并不是个好主意。

**Comment by yiray1** [comment]
您好，感谢您开发的这么好的浏览器，能否增加一个脚本开关功能呢亲来控制脚本对网页是否生效，不知从技术上可否实现呢，期待您能回复！

**Comment by tuyafeng** [comment]
脚本在即将到来的 4.2.9 重构了（不容易，那么多功能终于排期到了脚本），新的脚本管理支持单条脚本的启用禁用，每条脚本支持宽匹配多个链接，可以期待一下。

**Comment by tuyafeng** [comment]
快半年了，现在的脚本已经支持通配符了。更复杂的改动要在更后期了。
