### ISSUE TITLE
添加谷歌原生网页翻译

### ISSUE THREAD

**Issue by w311ang** [tuyafeng/Via#494]
有个[谷歌原生网页翻译](http://via-app.cn/#/pluginDetail/10)的插件，能否研究一下加进去？

**Comment by tuyafeng** [comment]
这个插件确实不错，之后会考虑添加。

**Comment by tuyafeng** [comment]
试用了之后，感觉并不是很理想，脚本好像并未针对国际化做优化，暂时不考虑了。
