### ISSUE TITLE
Add the ability to disable WebRTC

### ISSUE THREAD

**Issue by realmxsin** [tuyafeng/Via#496]
Hello!
I really like Via browser, it has many useful features.
But is it possible to add to the application privacy related features like disabling WebRTC?
Or (and) give the permission to manage some properties via chrome://flags?
Thank you :)

**Comment by tuyafeng** [comment]
Unfortunately, webview does not provide an interface to directly disable this feature, but the current version will reject all permission requests for webrtc.
