### ISSUE TITLE
Return "Page Info" button

### ISSUE THREAD

**Issue by Sh1Yo** [tuyafeng/Via#501]
It was very convenient to get info about a link without following it, but I don`t see this option after a few last updates.

**Comment by tuyafeng** [comment]
I will think about it.

**Comment by martintxoz** [comment]
Yes!! I'm suffering too the lack of this feature. I was accustomed to use it too. But I missed it from the last update. Please, restore it, or made something for us to view the URL of the link without clicking on it!!

**Comment by Sh1Yo** [comment]
Forgot to close, it is resolved for now.
