### ISSUE TITLE
Request for language

### ISSUE THREAD

**Issue by LouisUnnoficial** [tuyafeng/Via#504]
I would like to contribute to the Portuguese translation - Brazil

**Comment by tuyafeng** [comment]
I'm very grateful if you perfect the Portuguese localization. The following is how to do.

1. Fork this repository
2. Modify `app/src/main/res/values-pt/strings.xml` to perfect it
3. Make a Pull Request

**Comment by LouisUnnoficial** [comment]
First I need you to add "values-pt-rBR.xml" for me to fork

**Comment by tuyafeng** [comment]
You can do it in your forked repo, and then Make a PR to this repo after the modification is completed.
