### ISSUE TITLE
当一个标签页是base64编码的图片时，长按图片会出错

### ISSUE THREAD

**Issue by Jiaocz** [tuyafeng/Via#517]
如题，假如一个标签页的地址是base64编码的图片，长按图片不会出现图片菜单而是直接无响应然后崩溃，不知道为什么
_测试页面 [https://orangii.cn/pay.html](https://orangii.cn/pay.html) 点击右上角截图会生成一个类似图片页面，长按图片就无响应，如果没有生成成功可以刷新再试一次_

**Comment by tuyafeng** [comment]
收到问题。

**Comment by tuyafeng** [comment]
看起来似乎是因为 base64 链接过长，展示的时候崩溃了，这个目前来看也没有什么特别好的解决方案。

顺带一提，网站的类似需求可以直接告知用户使用手机截图。
