### ISSUE TITLE
Since the update Blue circle on the side ?

### ISSUE THREAD

**Issue by davidcal** [tuyafeng/Via#519]
It is very disturbing

**Comment by tuyafeng** [comment]
Can you tell me more detail about your device? Like model, android system version.

**Comment by davidcal** [comment]
xiaomi mi8 android 9

**Comment by davidcal** [comment]
#

**Comment by davidcal** [comment]
![Screenshot_2020-05-23-15-51-03-594_mark via gp](https://user-images.githubusercontent.com/5781331/82731247-15db0680-9d0e-11ea-89bf-8a4d18c5ffe6.jpg)
