### ISSUE TITLE
[bug] v4.0 后，不会重新打开之前的所有标签页

### ISSUE THREAD

**Issue by zwz** [tuyafeng/Via#530]
打开via，能够重新打开之前的所有标签页，这个功能非常有用
升级到4.0后，通常也都正常
但是如果有其他app中操作要访问网页，而打开了via中的一个新标签页后（浏览后，点击返回，会回到原来的app）
下一次再打开via，就只会打开一个默认的标签页，之前所有标签页全部丢失

**Comment by tuyafeng** [comment]
是不是开启了隐身模式，在隐身模式下不会恢复标签页。

**Comment by zwz** [comment]
但是之前版本即使是隐身模式
所有以前打开的标签页，在下一次重新打开的时候都会全部自动恢复的

**Comment by tuyafeng** [comment]
之前版本的隐身模式恢复标签，其实是 bug。隐身模式的设定就是不会保存标签的。

**Comment by zwz** [comment]
我的意思是：
我在隐身模式之前打开了很多标签（集合A）
然后继续使用过程中，进入了隐身模式，然后可能继续打开了一些标签（集合B）
以前的版本，会保留集合A（我个人觉得这是非常好的特点）
而现在的话，就全部没了

**Comment by tuyafeng** [comment]
(°ー°〃) 事实上，之前也有过很多人反馈说为什么总是恢复过期的标签，考虑到这个特性的迷惑，毕竟大家对功能的理解不会像你这样清晰（我这个开发者之前都没好好考虑过这个 = =），还是一刀切了隐身模式不恢复标签吧。

**Comment by zwz** [comment]
那么是不是可以考虑在设置中增加一项：自动打开上次的标签
这可能是更好的做法
