### ISSUE TITLE
''上一个标签''快捷键无法于其他标签切换至第一个标签

### ISSUE THREAD

**Issue by Dsp004** [tuyafeng/Via#535]
如题，设置在底边栏后退键上的长按快捷键''上一个标签''，无法于其他标签切换至标签页总览中最上方的标签页。
该快捷键于第一个标签切换至其他标签时能正常工作，设置于底边栏前进键的''下一个标签''快捷键也能正常工作。

**Comment by tuyafeng** [comment]
好的，收到。下个版本会修。

**Comment by tuyafeng** [comment]
最新的 4.0.2 版本已经修复该问题，故关闭。
