### ISSUE TITLE
可以在搜索栏或者地址栏增加一个扫码吗？

### ISSUE THREAD

**Issue by 276562578** [tuyafeng/Via#541]
经常有些需要扫二维码的，然后总是得用微信扫码之后再用本地浏览器打开，太费劲了，做成插件什么的也行呀

**Comment by tuyafeng** [comment]
其实是有个插件，可以搭配使用。[二维码扫描](https://coolapk.com/apk/mark.qrcode)

**Comment by 276562578** [comment]
感谢！建议将方法加到关于页面
