### ISSUE TITLE
书签自定义拖动排序问题

### ISSUE THREAD

**Issue by Lynhongchuan** [tuyafeng/Via#542]
环境：Emui10/Android 10
via 4.0.2
很久之前书签长按拖放排序功能就消失了 请问是因为稳定性/bug移除的还是有bug不能实现了？
之前版本一直没解决
是我设备问题吗？请问如何恢复实现？

**Comment by tuyafeng** [comment]
长按拖拽排序目前来看确实不太稳定，之后会完善。

**Comment by Lynhongchuan** [comment]
谢谢回复
