### ISSUE TITLE
建议添加预加载功能

### ISSUE THREAD

**Issue by 276562578** [tuyafeng/Via#543]
通过设置来控制开关，提前预加载可能打开的网页，进一步提升使用速度

**Comment by tuyafeng** [comment]
一般是预载什么网页呢？小说站点的「下一章」，新闻列表的「下一页」？

**Comment by 276562578** [comment]
小说的下一章是比较容易实现的，如果可以的话，比如搜索结果的前3-5个，一些页面内容为多个并列的前几项

**Comment by 276562578** [comment]
比如v2ex的前5个帖子这样的

**Comment by tuyafeng** [comment]
如果是预载搜索结果的话，我感觉意义不大，有些浪费流量猜用户点哪个的感觉，同时现在 Via 的前进后退栈的实现，也没法做到预载这么多结果的功能。

**Comment by 276562578** [comment]
好吧~_~，其实很多时候大家都不在乎流量了，如果能更快的打开一个网页其实意义更大

**Comment by tuyafeng** [comment]
重点不在「浪费流量」，在「猜用户」，当然流量能花在关键的地方是最好啦。

假设说现在在搜索，搜索页打开了，用户点击了第六个，这时正在缓存前五个结果，因为用户点击了所以撤掉缓存的加载，然后寻找新的要预载入的网页，这时用户返回到搜索页，重新加载前五个，结果用户打开了下一页搜索结果。

场景里网页的加载和撤销，新建与销毁，不仅折腾流量，还折腾性能。

**Comment by 276562578** [comment]
嗯，这么说来很有道理，性能与功能之间确实难平衡，可能对我这样的人宁愿牺牲性能换取自己的时间
