### ISSUE TITLE
反馈问题及功能建议：脚本有时候会失效。建议添加密码保存和自动填充

### ISSUE THREAD

**Issue by pbxs666** [tuyafeng/Via#544]
1.打开网页时，脚本有概率失效，不执行。有时候打开百度，广告脚本就不执行。

2.建议添加密码保存和自动填充。我一周清理一次（cookies，缓存之类能清的都清除了），这样每周都得登录一次网站，要登的网站还挺多😂，挺麻烦，建议添加密码保存和自动填充功能。

3.最后还想问下，作者平时是酷安，github，贴吧还是邮箱用的多点啊，以后好沟通呀😀。

**Comment by tuyafeng** [comment]
啊，我先回答最后一个，我没有活跃的社交平台，都是偶尔上去看看，如果需要及时沟通的话，可以加反馈群：915101678，这个是平常比较留意的。这段时间因为一直在忙 Via 广告拦截的重构，就没看 GitHub 的 issue，抱歉。

自动填充可以使用密码填充工具实现，但是因为一些未知的原因，国内版本的支持好像有些问题，可以使用 play 版本。

保存密码的话，危险操作，虽然你愿意相信我这个小个人开发者，但是我对自己代码的安全水平还是有自知之明的。

**Comment by pbxs666** [comment]
好的，谢谢啦！
那第一个问题？我很想知道via的脚本执行顺序。
广告脚本有时失效我觉得可能与其他脚本有关，因为现在很多脚本都是任意域名执行，而且脚本还死循环，无限调用。

**Comment by tuyafeng** [comment]
脚本执行顺序没有特殊处理，单纯安装安装先后来，匹配的脚本中，先安装的先执行。

**Comment by pbxs666** [comment]
好的，谢谢啦
