### ISSUE TITLE
今天更新之后，点击链接就崩溃

### ISSUE THREAD

**Issue by innerseacn** [tuyafeng/Via#552]
华为m3平板，昨天以前都没问题，今天更新后点击网页中的链接会经常性的崩溃，根本无法使用。
比如我在via官网下面的github链接点击就会崩溃，就是最近一次更新的问题，希望尽快解决。

另：导入书签不全，保存的后半部分书签都没有导入。

**Comment by innerseacn** [comment]
经过测试，发现问题出在建立新标签上，如果点击链接需要新建标签页则崩溃闪退，如果还是用原标签页打开链接则正常，手动长按链接选新窗口打开正常。

**Comment by tuyafeng** [comment]
收到问题，已在最新测试版修复，这两天就会发布，到时候更新就正常了。

如果急着解决，可以去更新华为的 webview，应该能解决问题。

**Comment by innerseacn** [comment]
问题已解决，感谢！
