### ISSUE TITLE
[Feature request]Scan/Load(from file manager) QR Code

### ISSUE THREAD

**Issue by Mitia99** [tuyafeng/Via#555]
Could you add load QR code(from camera and file manager)feature from the app.It will be more convenient than an external app.Thanks![Screenshot_20200715_210111.jpg](https://user-images.githubusercontent.com/56766778/87579483-a6b2da80-c6de-11ea-84f0-16a49305e9e2.jpg)

**Comment by tuyafeng** [comment]
Starting from version 4.3.4, Via has added a built-in QR code scanner. This issue can be closed.
