### ISSUE TITLE
[Suggestion]OneSky localization

### ISSUE THREAD

**Issue by Mitia99** [tuyafeng/Via#557]
Suggestion:
_Create onesky localization support(more convenient for people who want to help with the translation and doesn't understand github's localization method,like me)
_Add the onesky link at "about"

Benefits:faster localization

**Comment by tuyafeng** [comment]
If you are willing to translate a certain language and do not know how to do it, I can help you create the corresponding file, you only need to translate the specific fields.  The collaboration on github is very convenient and it is also the largest open source community, so I don't consider changing the platform for the time being.

**Comment by Mitia99** [comment]
@tuyafeng I wanna help for french translation but I don't know how to do it in github.It's okey if github's localization is already convenient.The issue can be closed.Thanks

**Comment by tuyafeng** [comment]
The following is a short description of how to improve French localization:

1. Fork this repository. (The following operations are performed in your forked repository).
2. Edit this file `app/src/main/res/values-fr/strings.xml` (It is a localization file for French).
3. Make a pull request after you complete the modification.

More details about localization:

`app/src/main/res/values/strings.xml` is default language file.
Translate a sentence, for example:

`<string name="action_new_tab">New tab</string>` (.../values/strings.xml)
`<string name="action_new_tab">Nouvel onglet</string>` (.../values-fr/strings.xml)

If there is no corresponding xml statement in the fr file, you can copy the corresponding statement from the default file and add it to the fr file. Please feel free to ask if you have any questions 😄
