### ISSUE TITLE
我希望通过网页打开app

### ISSUE THREAD

**Issue by Forty-nine** [tuyafeng/Via#560]
比如说我用via浏览推特，通过一个按钮自动打开推特客户端。
酷安有一个 app 。 https://www.coolapk.com/apk/com.mihotel.shareto
简单来说，我希望这个功能内置到 via

**Comment by tuyafeng** [comment]
长按菜单的分享按钮，会自动寻找可以手机中可以打开该页面的应用，试试看。

**Comment by Forty-nine** [comment]
> 长按菜单的分享按钮，会自动寻找可以手机中可以打开该页面的应用，试试看。

我才发现，感谢你。这种小技巧有没有一个相关的发布页整理？

**Comment by tuyafeng** [comment]
目前还没有，via 这种小彩蛋确实太多了，后续会想办法把这些彩蛋功能都直观地展示出来。
