### ISSUE TITLE
Can not download 

### ISSUE THREAD

**Issue by Conglinge** [tuyafeng/Via#572]
can not download from below link...
https://renzhezhilu.gitee.io/webp2jpg-online/
Edge can do it...

**Comment by Conglinge** [comment]
]

**Comment by Conglinge** [comment]
can not download from below link...
https://renzhezhilu.gitee.io/webp2jpg-online/
Edge can do it...

**Comment by Conglinge** [comment]
![Screenshot_2020-07-22-18-26-34-980_mark via](https://user-images.githubusercontent.com/59311899/88166030-2f82c680-cc49-11ea-98e9-62aeafbfd20a.jpg)
![Screenshot_2020-07-22-18-26-44-595_mark via](https://user-images.githubusercontent.com/59311899/88166035-33164d80-cc49-11ea-8a86-899318923273.jpg)

**Comment by tuyafeng** [comment]
The current version does not support the download of blob links.

**Comment by ronnac** [comment]
I would like to have this functionality, too.

**Comment by tuyafeng** [comment]
The new version now supports the blob protocol, and images from this website can be downloaded.
