### ISSUE TITLE
5th column in standard-homepage

### ISSUE THREAD

**Issue by Micha-he** [tuyafeng/Via#573]
Is there any way, to get a 5th column in the standard-homepage?

Maybe a idea for a custom CSS ?

**Comment by tuyafeng** [comment]
You can add the following code as custom CSS to achieve it. (P.S.: 360px = 72px *5)

```
@media only screen and (min-width: 360px)
#box_container {
    width: 360px;
}
```

**Comment by Micha-he** [comment]
Your CSS-example didn't change anything on my homepage. Left and right is and remaibs a wide empty border.

**Comment by tuyafeng** [comment]
Sorry for my carelessness😅, I am not very familiar with style sheets. The following code is correct.

```
@media only screen and (min-width: 360px) {
    #box_container {
        width: 360px;
    }
}
```

**Comment by Micha-he** [comment]
With the New css-code, the result is the same. Only 4 columns, a new additional link is added below the bottom (window-)border.
It didn't change anything...

**Comment by Micha-he** [comment]
This works:

@media only screen and (min-width:360px){#box_container{width: 360px;}}

The problem was the space after '#box_container' !

**Comment by tuyafeng** [comment]
Anyway, the problem is solved 😄
