### ISSUE TITLE
Delete empty advertising space.

### ISSUE THREAD

**Issue by Adrymate9** [tuyafeng/Via#575]
I would like to know if there is any possibility of eliminating the empty spaces left by the blocked advertising. Or if you plan to address the problem to fix it in the next updates. 

![107930695_220876](https://user-images.githubusercontent.com/53199368/88447448-c4342280-ce09-11ea-9932-92bcb7cb87c2.jpg)

**Comment by tuyafeng** [comment]
At present, I am also very helpless about the blank of the webpage. It seems that this is a problem caused by the fixed style sheet.

**Comment by t0n4** [comment]
> I would like to know if there is any possibility of eliminating the empty spaces left by the blocked advertising. Or if you plan to address the problem to fix it in the next updates.
> 
> ![107930695_220876](https://user-images.githubusercontent.com/53199368/88447448-c4342280-ce09-11ea-9932-92bcb7cb87c2.jpg)

Here are the Custom Filters for almost blank spaces:

`m.lacapital.com.ar##DIV#prestitial_layer
m.lacapital.com.ar##DIV#prestitiall_layer
m.lacapital.com.ar##DIV.ads-wrapper.ads-header-2020
m.lacapital.com.ar##DIV.ads-wrapper
m.lacapital.com.ar##DIV.banner-wrapper,DIV.news-header-social`

If you add this too, the site looks diferent
`m.lacapital.com.ar##SECTION.widget-full.news-header`

**Comment by Adrymate9** [comment]
Thanks for the support and the solution!
