### ISSUE TITLE
Fix "Block 3rd party cookies" option logic

### ISSUE THREAD

**Issue by Sh1Yo** [tuyafeng/Via#580]
When "Block 3rd party cookies" is enabled the browser accepts 3rd party cookies and when this option is disabled the browser rejects 3rd party cookies.
You can check it there - https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled

**Comment by kae-sakura** [comment]
I think so

**Comment by lfom** [comment]
Yeah, it needs to be fixed. Simpy change "Block" to "Accept" in the settings text.

**Comment by tuyafeng** [comment]
I was too careless, I am so sorry, the next version will fix it, you saved my life.

**Comment by lfom** [comment]
@tuyafeng Please also consider adding an option in settings to "Force enable zoom" so the zoom gesture works on any pages, and maybe a work-around for Reader mode: open the page with [Textsize](https://www.textise.net/) (please take a look at their bookmarlet). Thanks.

**Comment by kae-sakura** [comment]
> I was too careless, I am so sorry, the next version will fix it, you saved my life.

fix is only text?

**Comment by tuyafeng** [comment]
> > I was too careless, I am so sorry, the next version will fix it, you saved my life.
> 
> fix is only text?

No, I corrected the logic and the text has not changed.

**Comment by kae-sakura** [comment]
ok. thanks

**Comment by Sh1Yo** [comment]
Fixed in 4.0.5
