### ISSUE TITLE
Ads Redirect

### ISSUE THREAD

**Issue by Jamir03** [tuyafeng/Via#581]
Uhmm.. Website that have redirect ads,that redirect you to another website please let it be in another tab it affects video playing because it would reload the whole site.Thanks!

**Comment by himawansyahputro** [comment]
> Uhmm.. Website that have redirect ads,that redirect you to another website please let it be in another tab it affects video playing because it would reload the whole site.Thanks!

Can you give an example?

**Comment by tuyafeng** [comment]
The current version has already fixed this problem.
