### ISSUE TITLE
Via search often/too much

### ISSUE THREAD

**Issue by Micha-he** [tuyafeng/Via#584]
If I open a local address in my network (http://posttorhnr/csv?tasknr=1), Via tries to search for this address with Google. I can open the device only with the IP-address.

Some versions back, this problem doesn't exists.

If you can't change this behaviour, can I disable the search with the URL-field?

**Comment by Sh1Yo** [comment]
I am agree, after a few new versions it is impossible to open websites with punycode.

**Comment by tuyafeng** [comment]
Okay, I will improve it in the next version. I will also add punycode support. @Sh1Yo

**Comment by Micha-he** [comment]
Only a info: Still not working in version 4.0.5.

**Comment by Micha-he** [comment]
Please make it switchable :-) I can't access my OpenHAB-server via "http:\\openhabianpi:8080" with Via !

**Comment by tuyafeng** [comment]
I will fix it in the next version(4.0.6).

**Comment by Micha-he** [comment]
Not work in 4.0.6 !

**Comment by tuyafeng** [comment]
Sorry, can you give me your email address? I will rebuild a package for you.

**Comment by CHRisDeDisk** [comment]
I can agree: Access to LAN hosts does not work by DNS/DHCP hostname resolving (not even by changing etc/hosts). Please fix this behavior.

**Comment by Micha-he** [comment]
Unfortunately nothing has improved in V4.0.7

**Comment by Micha-he** [comment]
also V4.0.8 isn't better...

**Comment by tuyafeng** [comment]
Are you sure?  The current 4.0.8 version fixes this problem.

**Comment by Micha-he** [comment]
Yes, I'am sure! Same behavior as the last versions.

I'cant access my IOT-Wifi-devices with e.g. 'http://sw001' (but DNS-resolution works). And it works, if I access with FQN like 'http://sw001.fritz.box'

**Comment by tuyafeng** [comment]
Well, I ignored the numbers, it will be fixed in the next version 4.0.9.

**Comment by Micha-he** [comment]
And adresses also not work, if 'http://'-prefix is missing. Can you this modify too?

**Comment by tuyafeng** [comment]
For these special links, the protocol header is necessary. The only link that does not need to be judged is localhost, except that the browser cannot confirm it.

**Comment by Micha-he** [comment]
Maybe you can:

1. Add an option to disable the search in the address-bar
2. Add an option to auto-prefix 'http://', if the user doesn't specified a protocol

**Comment by Micha-he** [comment]
In the last version 'http://sw001' seems to work, but 'http://sw009-9' doesn't!
