### ISSUE TITLE
[Bug] Cannot open link in new tab.

### ISSUE THREAD

**Issue by Bulk-204** [tuyafeng/Via#587]
Since last update, there is a bug in browser.
In Javascript a code that use to open link in new tab. But this code doesn’t work in browser Javascript.
Example:
`window.open("https://google.com");` 
This code works in Chrome, Firefox,All others browser, but doesn’t work in Via. It is a serious issue. Fix it.

**Comment by tuyafeng** [comment]
Got it. I will fix it in the next version.
