### ISSUE TITLE
图片下载能否直接从已加载页面中提取？

### ISSUE THREAD

**Issue by fuze35** [tuyafeng/Via#588]
像pixiv这种有防盗链机制的网站下载图片会返回403错误导致无法下载。能否像edge那样直接从已加载的页面中下载下来？这样也比较节省流量。

**Comment by tuyafeng** [comment]
受限于 webview 的碎片化，从缓存中提取并不可靠。

**Comment by fuze35** [comment]
了解。如果能有其他的方法解决pixiv下载403问题就更好了。祝愿via越做越好。
