### ISSUE TITLE
Publish the application source code or collaborate for free

### ISSUE THREAD

**Issue by Cutetlaem** [tuyafeng/Via#590]
Hello,
I like this browser very much, but every time I update to a new version, the functions that I want are not seen. Therefore, I have to manually edit the APK file to get the functionality that I desire.
This is a version I edited, I fixed in version 4.0.2, including:

- Improved ad blocking, including ads on Youtube (including www.youtube.com and m.youtube.com. Promotional videos, banner ads below and inside videos,... will now is no longer appearing, rather, it cannot be seen) and many other websites like Yahoo, Reddit, Quora, and adult websites,...
- Improved search engine, eliminating unnecessary parameters.
- Improve the quality of Vietnamese translations.
- Support moving apps to SD card.
- Support install to Android 10 (SDK 29), tested on my device, it works fine.

Here is the download link for the version I edited: https://drive.google.com/file/d/1O9rvjHjh37tB5JIW8m_8aI76v-y4amel/view?usp=sharing
If possible, I hope you source this application publicly or you can allow me to contribute to the development of the application, I would be grateful for that.

**Comment by lfom** [comment]
Do you have an updated version using latest Via version you could share, please? I would like to test it since I cannot play YouTube videos  correctly on my phone using Via anymore. Thanks.

**Comment by Cutetlaem** [comment]
> Do you have an updated version using latest Via version you could share, please? I would like to test it since I cannot play YouTube videos correctly on my phone using Via anymore. Thanks.

I will do it the next time. However, if you can't play YouTube videos, try updating `Android System Webview` (or `Android WebView` on some devices). Download link here: https://play.google.com/store/apps/details?id=com.google.android.webview
Via browser depends on it, without it, Via will not work.

**Comment by tuyafeng** [comment]
The current code is not perfect, so let's talk about it later.

At the same time, regarding your improvements, I will explain one by one:
-Ad rules already support subscription, you can choose the rules of subscription as needed
-If the current built-in search engine is not perfect, you can bring it up and I will improve
-About localization improvements, just make a PR directly
-Moving to the sd card, I don’t know much about this, do I need to set specific parameters?
-In the next version (4.0.6), targetApi will be upgraded to 30 (Android 11)

**Comment by Cutetlaem** [comment]
> The current code is not perfect, so let's talk about it later.
> 
> At the same time, regarding your improvements, I will explain one by one:
> -Ad rules already support subscription, you can choose the rules of subscription as needed
> -If the current built-in search engine is not perfect, you can bring it up and I will improve
> -About localization improvements, just make a PR directly
> -Moving to the sd card, I don’t know much about this, do I need to set specific parameters?
> -In the next version (4.0.6), targetApi will be upgraded to 30 (Android 11)

> To support installing to SD card, please use `android:installLocation="auto"`, it does not affect devices that don't support / don't insert SD card. Documentation here: https://developer.android.com/guide/topics/data/install-location

> Improved ad blocking: Instead of just blocking ad links / domains, I added class / id attribute blocking of some websites. The long press -> "Mark as ads" feature on most phone browser apps works really badly, it's incredibly simple to bypass it. For example, nest the ad tag in multiple <div> tags, then the parent <div> tags containing the ad tag just don't assign the class / id attribute, the "Mark as ads" feature will not be able to detect is tagged advertising, instead, it will mark the entire container into an advertising tag. Ex:

```
<body>
   <div class="container">
      <div>
         <div>
            <div class="website-ads-attribute">
               ......sth.....
            </div>
         </div>
      <div>
   </div>
</body>
```
If you use the "Mark as advertisement" feature here, the class `container` will be the "victim" of this feature.

> Also, because I don't have the source code, I can't add the "Download to SD card" feature, which is quite sorry about this.
