### ISSUE TITLE
Request Better block pop-up/redirect by ads

### ISSUE THREAD

**Issue by Iquaridys** [tuyafeng/Via#595]
Hi i like this browser and use it to my main browser phone.

i try put this tampermonkey file in VIA browser javascript but no work.

can someone help me to change this,
https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
to pure javascript, so can work fine in VIA browser?

this file from Adguard for details go this github : [Adguard](https://github.com/AdguardTeam/PopupBlocker)

thanks before.

**Comment by kontilan** [comment]
https://github.com/tuyafeng/Via/issues/245

**Comment by tuyafeng** [comment]
If it’s just for ad blocking, why not just subscribe to the adblock filters?
