### ISSUE TITLE
个别网站广告无法拦截的问题

### ISSUE THREAD

**Issue by zllafgafg** [tuyafeng/Via#602]
你好，我开启了via浏览器的广告拦截订阅规则，也更新了相关规则，基本上是可以用的，但是在手机中国这个网站上，里面的广告不能拦截。我添加了好几个拦截订阅，都尝试了，也不行。我用了vivaldi浏览器，发现它自己自带的广告拦截可以拦截屏蔽掉手机中国的广告。所以希望以后能够优化一下，谢谢。
![Screenshot_20200901-222347](https://user-images.githubusercontent.com/61912416/91865828-5f8ba380-eca4-11ea-911a-5bfe0bc81991.jpg)
广告如图片所示。

**Comment by zllafgafg** [comment]
而且在这个网站上，将其标记广告也不行，标记广告没有反应。

**Comment by zllafgafg** [comment]
你好，我还发现在丝芙兰中国的网站上，首页的展示页面会被误标记为广告，关闭默认的那个订阅规则也不行，必须把广告拦截关闭掉，才可以正常显示。
![IMG_20200902_211804](https://user-images.githubusercontent.com/61912416/91989023-9627f380-ed62-11ea-8f1d-7caf27f9fa78.jpg)

**Comment by tuyafeng** [comment]
丝芙兰中国那个误杀的规则已经移除了，手机中国这个确实还有点问题，我之后再研究看看。

**Comment by zllafgafg** [comment]
好的，谢谢。
