### ISSUE TITLE
Built-in QrCode Scanner

### ISSUE THREAD

**Issue by erzqy** [tuyafeng/Via#609]
QrCode most feature that needed today. 
Hope this feature available soon in Via browser.

**Comment by Geeyun-JY3** [comment]
You can try the [QrCodeScan](https://play.google.com/store/apps/details?id=mark.qrcode) also developed by @tuyafeng.

**Comment by Mitia99** [comment]
@Geeyun-JY3 There are many good QR third party apps but a built-in will be convenient.

**Comment by KrasnayaPloshchad** [comment]
Another possible solution is integrating camera, so Via Browser would be able to make use of webcam to scan code via https://qrcoddscan.in, https://qrsnapper.com etc.

**Comment by tuyafeng** [comment]
Starting from version 4.3.4, Via has added a built-in QR code scanner. This issue can be closed.
