### ISSUE TITLE
输入网址时推荐历史记录的顺序问题

### ISSUE THREAD

**Issue by Young-Lord** [tuyafeng/Via#618]
首先，依次访问下列网址：
example.com/num1
example.com/num2
example.com/num3

此时地址栏中输入example.com，推荐的网页顺序为（从上到下）：
example.com/num1
example.com/num2
example.com/num3

而此时再次访问example.com/num1，然后在地址栏中输入example.com，离输入框最近的是example.com/num2，而example.com/num1则成为离输入框最远（即最靠下）的推荐

**Comment by tuyafeng** [comment]
好的，之后会优化这个顺序。

**Comment by tuyafeng** [comment]
新版本(5.0.7)已优化。
