### ISSUE TITLE
- Request - Adblocker options

### ISSUE THREAD

**Issue by rafaelsturmer** [tuyafeng/Via#62]
Adblocker needs a "allow ads in this site" option

**Comment by KairusDarkSeeker** [comment]
You mean AdBlock Whitelist?

**Comment by rafaelsturmer** [comment]
yes

**Comment by halcion** [comment]
need better ad block selector. the current one always blocks the parent class and results in blanking out the entire page not the ad image or just the containing ad frame. i have been unsuccessful to "mark as ad" not even one time in all my attempts.

**Comment by tuyafeng** [comment]
I will add this option to the "Site conf" of the app later.

**Comment by Mitia99** [comment]
@tuyafeng This feature is really a priority for a browser.Thanks for considering it.
