### ISSUE TITLE
feature suggestion: "use volume keys to switch through tabs"

### ISSUE THREAD

**Issue by furkanunluturkk** [tuyafeng/Via#627]
tab switching is just a user pain. but utilizing the volume keys could be a great idea! thus we are not gonna be have to tap the same button every time to switch to another tab.
lets say we're on the 2th tab;
volume up : 3th tab
volume down : 1th tab
that'd be a killer feature especially for portrait activity.

**Comment by Mitia99** [comment]
@furkanunluturkk How about playing media in the browser?There will be conflict with volume action.I don't think that it is going to be added.

**Comment by furkanunluturkk** [comment]
> @furkanunluturkk How about playing media in the browser?There will be conflict with volume action.I don't think that it is going to be added.

yeah, i should have thought that. but switching tabs should be easier. "tabs" icon can be utilized with swipe gestures.

**Comment by tuyafeng** [comment]
I suggest that you bind the operation of switching tabs to the long press event (Settings-General-Gesture). Switching tabs is not too frequent operation compared to page sliding.
