### ISSUE TITLE
Go back to the old ad blocker

### ISSUE THREAD

**Issue by Cutetlaem** [tuyafeng/Via#634]
The latest version seems to have changed the ad blocking method, no more use of the hosts.txt file. However, the ad blocker does not currently block some sites / properties of the site as before.
I opened the file simple.txt, I don't really understand the symbols in it (for example: `@@||`, `||`, `~`,...). Do you have documents about it?
I think, instead of changing all ad blockers nowadays, you are only improving ad blockers in the past.

**Comment by tuyafeng** [comment]
Limited by the weak mechanism of hosts, it is difficult to make further breakthroughs, so I changed the entire ad blocking system, which is very convenient, you only need to subscribe to the source you need. If you want to know how to write rules, you can refer to: https://help.eyeo.com/en/adblockplus/how-to-write-filters
