### ISSUE TITLE
play版via浏览器下载软件无法在浏览器内安装

### ISSUE THREAD

**Issue by authon** [tuyafeng/Via#639]
play版via浏览器下载软件无法在浏览器内安装

在手机管理器里面安装没问题

手机mate30 pro

**Comment by tuyafeng** [comment]
现在最新版本（4.0.8）依旧无法安装应用吗？请给予 Via 安装未知应用权限和读写存储权限。

**Comment by authon** [comment]
> 现在最新版本（4.0.8）依旧无法安装应用吗？请给予 Via 安装未知应用权限和读写存储权限。

今天安装了个软件，可以了，赞
