### ISSUE TITLE
user-agent

### ISSUE THREAD

**Issue by jing0523** [tuyafeng/Via#648]
hello 
因为我们需要基于您的浏览器做跳转后续的开发，需要识别您所开发浏览器的user -agent, 请问目前是否支持区别于Chrome的浏览器user-agent, 以便我们可以区别于其他浏览器呢？

**Comment by tuyafeng** [comment]
啊？我觉得没有必要做这样的处理，因为在 android 5.0 以上系统中，via 的表现其实完全基于 chromium 的内核版本，当成 Chrome 就适配就可以了。
