### ISSUE TITLE
Enlarge text areas

### ISSUE THREAD

**Issue by solokot** [tuyafeng/Via#650]
Hello!

Please consider adapting the interface for multi-letter languages (such as Russian):
1) Button captions in the main/tools menu in two lines. Previously, the 3th party Via mod was done; it shows that the second line don't broke the menu layout, but fully displays the caption text.
![1](https://user-images.githubusercontent.com/25316928/99116722-91ef4080-2605-11eb-96b8-6c93f03b2e15.jpg)
![2](https://user-images.githubusercontent.com/25316928/99116725-93206d80-2605-11eb-8b73-62effd2eb029.jpg)

2) Extend the block of the pop-up context menu when browsing pages to the width of the screen (as in the settings) or make it possible to wrap the text of the menu item on the second line instead of cutting it off.
![3](https://user-images.githubusercontent.com/25316928/99116726-93206d80-2605-11eb-9b15-a5062a81b000.jpg)
![4](https://user-images.githubusercontent.com/25316928/99116728-93b90400-2605-11eb-910c-f37b682a6d06.jpg)

Thanks

**Comment by tuyafeng** [comment]
Okay, the caption in Russian is really long enough😂😂. The next version (4.0.9) will be optimized.

**Comment by solokot** [comment]
Perfect, thank you!
