### ISSUE TITLE
Ad blocking filters doesn't work with wildcard domains and root domain

### ISSUE THREAD

**Issue by Cutetlaem** [tuyafeng/Via#651]
There are 2 problems with ad-blocking custom filters, as follows:
#
**Block root domain with subdomain:**
I want to block the domain name `example.com` and its entire subdomains, I tried adding the following filter to custom filters: 

1. `*.example.com` -> Not blocked both the root domain and the subdomain. .

2. `.example.com` -> Not blocked both the root domain and the subdomain. .

3. `example.com` -> Only block `example.com`, subdomain not block.

**Block element on root domain with subdomain:**
I want to block the class `.ads-eg-class` on the website `example.com` and its entire subdomain (eg `www.example.com`). I added a custom filter:

1. `.example.com##.ads-eg-class` -> The element is not blocked on both the root domain and the subdomain.

2. `*.example.com##.ads-eg-class` -> The element is not blocked on both the root domain and the subdomain.

3. `example.com##.ads-eg-class` -> The element is only blocked on the root domain, not blocked on the subdomain.
#
I am using the latest version (4.0.8). Is there a solution to this problem?

**Comment by Cutetlaem** [comment]
**REGEX also doesn't work:**
I want to block an element of a website and on all its second level domain (SLDs), for example: I want to block id `#ads` on `google.com` and all SLDs like `google.com.vn`, `google. com.cn`,...
I wrote the regex as follows: `google.com(?:\.[^.]{2,3})?$###ads`.
I checked the regex above, it works as I would like (matching `google.com` and its SLDs) but it doesn't work in this case. The `#ads` element is not blocked!
Do you have a solution for this?
There is one more case: I want to block all domains `exam-ads-domain-(random text/number).tld` and its subdomains. How do I do this?

**Comment by tuyafeng** [comment]
The reason for the first problem:

Before each request, the url and from will be checked. If the user takes the initiative to open a webpage, such as the a.example.com you mentioned, at this time, url == from, and it will not be matched in the filter repository. The reason for this is that if you just want to visit some advertising links (take the initiative to visit), then I should not return you to a blank page. If I comment this check, all this is no different from normal Adblock.

```
private RequestFilter matchedRequest(String url, int type, String from) {
        if (isLoading || url.isEmpty() || url.equals(from)) {
            return null;
        }

}
```

**Comment by tuyafeng** [comment]
`example.com##.ads-eg-class` will work on both the root domain and the subdomain. Element filters do not support wildcards (the official instructions are). Element filters can only be used for global and specific domain names. If you need to apply it to multiple domain names, you can do this: `a.example.com,b.example.com##.ads`

**Comment by tuyafeng** [comment]
The request filter does not support regular expressions. You can use wildcards instead. Even the official easylist only has a few regular expression filters. I don't think it is worth sacrificing performance for these filters. The element filter does not support regular expressions.

**Comment by Cutetlaem** [comment]
That is the limitation of Adblock Plus, for example with the Google domains, they use a lot of TLD, SLD, listing them is very difficult and long. Why don't you try to switch to AdGuard AdBlock, which supports wildcard and regex?

**Comment by tuyafeng** [comment]
This design is mainly for performance considerations, and it can also be compatible with the existing abp rules. There is nothing wrong with this.
