### ISSUE TITLE
可以独立设置每一个标签页的模式吗?

### ISSUE THREAD

**Issue by Subfire** [tuyafeng/Via#652]
可以独立设置每一个标签页的模式吗? 比如标签A需要手机模式, 标签B需要电脑模式.

**Comment by tuyafeng** [comment]
现在，你可以为每个网站设置自己的特定设置，比如电脑模式，只需要 1. 访问该网站，2. 点击左上角的放大镜或是小盾牌图形，3. 启用并单独设置各项。
