### ISSUE TITLE
FeatureRequest "anti anti adblocker"?

### ISSUE THREAD

**Issue by himawansyahputro** [tuyafeng/Via#654]
Hi Tufayeng thanks for via browser, i like it very much
can you please add this feature? 
(i know it needs tampermonkey/grease monkey or other scriptmanager out there to be implemented in via browser), but is there a way to implement "anti anti adblocker"/"anti adblock killer" on via browser?

http://reek.github.io/anti-adblock-killer/#filterlist

example of a website that block adblock users
http://megaurl.in/Fd8cODx

reference:
https://clearcode.cc/blog/detect-ad-blockers/
https://thenextweb.com/apps/2016/02/11/around-and-around-we-go/amp/
https://themeisle.com/blog/best-anti-adblock-wordpress-plugins/

**Comment by tuyafeng** [comment]
You can subscribe to this list directly on the settings page(Settings -> Genral -> Ad blocking -> Filter subscriptions).

**Comment by himawansyahputro** [comment]
I'm using via 4.0.9 
I cannot subcribe it, only add but can't update

https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer-filters.txt

**Comment by tuyafeng** [comment]
Please use this link:
https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

By the way, you can turn off adblock separately for sites those anti-adblock. You can set it in the site configuration, or you can click the 🔍 or 🛡️ icon in the address bar when you open the site.

**Comment by himawansyahputro** [comment]
thanks, I'm using v 4.1.6 and now it's working 👍
