### ISSUE TITLE
[NewFeatureRequest] Save Browsing Session Feature

### ISSUE THREAD

**Issue by himawansyahputro** [tuyafeng/Via#667]
It will be a great thing if this feature is implemented in via browser,

"Sessions: Manage Sessions Manually"
browser allows users to save a string of opened tabs as a Session, which can be named an opened in the future, 
We can also name the session, edit opened tabs from the saved session we choose, so we can easily remember and organize multiple sessions.

screenshot:
https://assets-hongkiat-com.cdn.ampproject.org/i/s/assets.hongkiat.com/uploads/cool-vivaldi-browser-features/7-sessions-manage-sessions-manually.jpg

**Comment by tuyafeng** [comment]
This is a very strange feature.
