### ISSUE TITLE
Status bar disappears after exiting full screen on notched devices.

### ISSUE THREAD

**Issue by demonff1** [tuyafeng/Via#672]
If u enter fullscreen to watch a video and then exit 
The fullscreen then the time, battery icon etc. on my status bar disappears. I have checked with other apps but it doesn't show bug. So the problem lies in via. Here is a before and after screenshot of what is happening: 

![Screenshot_2020-12-04-00-54-04-140_mark via gp](https://user-images.githubusercontent.com/68889858/101075059-b66a8700-35cb-11eb-905c-20e7e7b3a17b.jpg)

![Screenshot_2020-12-04-00-54-15-535_mark via gp](https://user-images.githubusercontent.com/68889858/101075081-bd919500-35cb-11eb-817c-c2c3acdb5522.jpg)

**Comment by tuyafeng** [comment]
Can you tell me your phone model and android version?

**Comment by demonff1** [comment]
Device: Redmi 8
Android 10
