### ISSUE TITLE
[Bug 4.0.9]Missing System Volume bar

### ISSUE THREAD

**Issue by Mitia99** [tuyafeng/Via#673]
Dear dev,

The system volume bar is missing when hitting button volume.

_Device: Huawei P30
_Android 10(Emui 10.1)

I hope that you would fix that.

**Comment by tuyafeng** [comment]
Have you turned on the full screen mode of the tools menu?

**Comment by Mitia99** [comment]
@tuyafeng I didn't change settings.

**Comment by Mitia99** [comment]
Seems like it have been fixed.Thanks

**Comment by tuyafeng** [comment]
Have you turned on "Settings - General - Gesture - Volume Keys to Scroll"?

**Comment by Mitia99** [comment]
@tuyafeng No,I didn't.

It is really a random bug.Maybe,it just need some improvements.

**Comment by tuyafeng** [comment]
Well, please make sure you are using the latest version. The latest version of Via is 4.1.6. I did change the relevant code a few versions ago. The latest version should be normal.

**Comment by Mitia99** [comment]
@tuyafeng Thank you for the update.It seems like the issue has been fixed but I didn't notice it since it was an issue a long time ago.
