### ISSUE TITLE
打不开本地网页

### ISSUE THREAD

**Issue by w-jin** [tuyafeng/Via#677]
设备：matepad
系统：emui11
打开方式：地址栏输入file:///storage/emulated/0/index.html
错误码：net::ERR_ACCESS_DENIED
此外，从文件管理器中选择via打开会显示源代码，不能渲染网页。

**Comment by tuyafeng** [comment]
很抱歉，android11 的存储策略十分严苛，Via 已经无法直接读取外置文件了，你可以选择系统的文件管理器，调用 Via 打开，Via 会将 html 文件拷贝一份文件的副本存在私有存储空间，并且，那样打开之后的链接，在 Via 被卸载前都是有效的。

**Comment by ugenehan** [comment]
> 很抱歉，android11 的存储策略十分严苛，Via 已经无法直接读取外置文件了，你可以选择系统的文件管理器，调用 Via 打开，Via 会将 html 文件拷贝一份文件的副本存在私有存储空间，并且，那样打开之后的链接，在 Via 被卸载前都是有效的。

用MT打开，选择kiwi或夸克，是可以的。但是同样用MT打开，选择via，就会提示错误。
私有存储地址是什么，可以将文件拷贝过去。

**Comment by tuyafeng** [comment]
这个问题目前简单的方式是，将应用强制使用传统的存储方式，但是那样的做法并不优雅，后续会专门处理这个问题。

如果希望快速解决的话，可以使用「质感文件」将主页文件夹的归属分配到 Via。或者将文件拷贝到 `/sdcard/Android/data/mark.via/files` 目录，再将 `file:///sdcard/Android/data/mark.via/files/homepage/index.html` 设置为主页。

**Comment by sonichy** [comment]
不能读取外部文件，怎么可能。
Via 在 MIUI 的 Android10 也不行，我自己做的浏览器却可以(https://github.com/sonichy/Android_HTYBrowser)。
