### ISSUE TITLE
有完整的项目么？

### ISSUE THREAD

**Issue by hec9527** [tuyafeng/Via#681]
我看这个项目只有一个分支，也只有一个 i18n 的文件夹，看来这不是via浏览器的仓库，我想知道via是如何做到打包后这么小的，我写一个hello world压缩后都1.6Mb

**Comment by SoyaLeaf** [comment]
在Gradle里移除 androidx 或者support库的依赖~ 但是AppCompatActivity 将不可用了~

**Comment by hec9527** [comment]
也就是在项目中不能使用安卓的视图，只能用一个webview 吗

**Comment by tuyafeng** [comment]
少用并且尽可能不用第三方库，回到刀耕火种时代的编码方式。
