### ISSUE TITLE
我想可以更换标签的位置

### ISSUE THREAD

**Issue by JacobHu0723** [tuyafeng/Via#684]
我想可以更换标签的上下位置，可以调整顺序，希望可以加入这样的功能。谢谢！

**Comment by Re00** [comment]
操作手势添加上滑手势，如底部工具栏上滑显示标签或者主页（可自定义）这样的功能可以添加么

**Comment by tuyafeng** [comment]
是什么时候希望变更标签顺序呢？我很好奇。

**Comment by JacobHu0723** [comment]
比如在启用一大堆标签页时，一些标签页位置可能太靠上，切换时不方便，想通过例如长按标签拖拽这样的方式来重新排序

tuyafeng <notifications@github.com> 于2020年12月31日周四 下午1:07写道：

**Comment by tuyafeng** [comment]
> 操作手势添加上滑手势，如底部工具栏上滑显示标签或者主页（可自定义）这样的功能可以添加么

底部工具栏上滑的手势没有添加，但是添加了滑动工具栏的，可以在「操作设定」里自行设置功能作用。我觉得打开主页还是直接点击按钮最实在，毕竟你的手指都移动到底栏那了。

**Comment by tuyafeng** [comment]
> 比如在启用一大堆标签页时，一些标签页位置可能太靠上，切换时不方便，想通过例如长按标签拖拽这样的方式来重新排序

很好奇，打开了太多标签，是在查找资料的时候吗，现在一屏在常规的竖屏下大概可以容纳 11 个标签，标签之间切换暂时还好吧，现在标签的实现有对位置的依赖，所以暂时是不会考虑标签拖拽排序了，下个版本 4.1.7 会添加快捷键支持，可以通过 ctrl 1~9 的组合键切换标签，算是个折中的解决方案。
