### ISSUE TITLE
安卓下的chrome和firefox都可以后台播放音频/视频,Via也有可能做到吗

### ISSUE THREAD

**Issue by yeezylife** [tuyafeng/Via#688]
我寻思了一下,Via的内核和chrome一样,那为啥chrome能后台放视频via不行呢,甚至前台切换了标签都会停.
有可能做到后台播放音频/视频吗

**Comment by tuyafeng** [comment]
可以做到，但是这样的表现不奇怪吗？打开视频，暂停应用，结果视频还在播放。

**Comment by yeezylife** [comment]
> 可以做到，但是这样的表现不奇怪吗？打开视频，暂停应用，结果视频还在播放。
有时候吃饭看新闻，但实际上不需要一直盯着屏幕。。或者网易云搜一首歌后台播放。。
可以参考chrome和kiwi浏览器，在内容设置里-后台播放 开/关 默认关闭。

**Comment by yeezylife** [comment]
我觉得后台播放的需求肯定是有的，bilibili不也有后台播放功能么…

**Comment by tuyafeng** [comment]
之后我也加个开关吧。

**Comment by dbthreee** [comment]
添加了吗，我怎么还是没找到

**Comment by HachimanDayo** [comment]
同意

**Comment by 7binggan** [comment]
还是没有后台播放，甚至换个标签页就停止了
