### ISSUE TITLE
Translate pages no longer work

### ISSUE THREAD

**Issue by AlbahrawyTiger** [tuyafeng/Via#693]
Use the latest version 4.0.9 on Android 4.4.2 and for two weeks or more, webpage translation does not work.When you press the translate button, the traffic is actually consumed, but the translation in progress does not appear at the top of the page.

**Comment by tuyafeng** [comment]
Can you provide relevant URL links?

**Comment by AlbahrawyAlalimi** [comment]
There is no specific url address translation does not work on, all url links without exceptions are not translated, for example this link does not work https://www.vpnbook.com/features

**Comment by tuyafeng** [comment]
This issue has been fixed, I will close it.
