### ISSUE TITLE
There is a security issue when verify domain certificate 

### ISSUE THREAD

**Issue by qingxp9** [tuyafeng/Via#706]
When a user is suffering MITM attacks and trying to access an HTTPS URL, Via should display a security alert to remind users that the certificate has been replaced by hackers.

When I replaced it with a Self-signed certificate, via has displayed a security alert as expected.
![image](https://user-images.githubusercontent.com/2822242/103994435-fa0b6e80-51d1-11eb-91c5-ed0d3162a343.png)

But when I replace it with a trusted certificate that belongs to another domain, there is no security alert. That means Via doesn't check whether the certificate matches the site user is browsing. 

https://user-images.githubusercontent.com/2822242/103996123-596a7e00-51d4-11eb-9315-eccc712ce7d1.mp4

So the attacker can use a trusted domain certificate with a wrong URL to bypass the security alert When doing MITM attacks.

Tested on Android Via APP 3.9.2 and 4.0.8 version.

**Comment by qingxp9** [comment]
？

**Comment by marksjc** [comment]
This is one symptom I think.  All web sites reached cause error "certifiate on this website is not trusted..." You can deny or accept I think.  Accept leads to additional iterations may not 
be resolvedd.  Deny/reject closes warning but next page will again have warning.  This happens to me on every new page even same site (essentially making browser unusable

**Comment by tuyafeng** [comment]
By default, Via will ignore secondary SSL error. If you need to ensure absolute certificate security while browsing, you can enable "Ignore secondary SSL error" in Via’s advanced settings.

**Comment by qingxp9** [comment]
What's the reason to ignore SSL error as default?
