### ISSUE TITLE
作为前端开发，如何适配 Via 的 「操作栏颜色自适应」？

### ISSUE THREAD

**Issue by GoFly233** [tuyafeng/Via#707]
比如说 [FurryTown Demo](https://ft_pre.gfmc.top) 这个页面
第一次打开的时候操作栏颜色是正常的，但是如果下滑页面后再刷新页面颜色就无法正常自适应，尝试过添加 1px 高度的 div（与应用栏相同颜色），但没有效果
附图：
![Screenshot_20210109_001307_mark via](https://user-images.githubusercontent.com/38996248/104037328-8be59c80-520f-11eb-9584-1051b9560616.jpg)
第一次打开时没有问题
![Screenshot_20210109_001340_mark via](https://user-images.githubusercontent.com/38996248/104037364-9a33b880-520f-11eb-8c2a-1673860c2e0a.jpg)
下滑后刷新无法自适应
![Screenshot_20210109_001345_mark via](https://user-images.githubusercontent.com/38996248/104037382-a3248a00-520f-11eb-8460-2e9fe208d3dd.jpg)
即使将页面重新上滑到顶部也无法自适应

**Comment by tuyafeng** [comment]
为了不影响网页加载的流畅度，Via 并不是获取网页 meta 标签来取色，而是直接去当前视图左上角 1px 的像素颜色，通常这不需要网站做什么适配工作。对于你提到的网页中部刷新页面取色失效的问题，可能是因为网页视图实际上超出了屏幕高度，所以左上角是背景灰，这个我后续会优化下，应该是去当前展示部分的左上角一个像素的颜色值。

**Comment by GoFly233** [comment]
> 
> 
> 为了不影响网页加载的流畅度，Via 并不是获取网页 meta 标签来取色，而是直接去当前视图左上角 1px 的像素颜色，通常这不需要网站做什么适配工作。对于你提到的网页中部刷新页面取色失效的问题，可能是因为网页视图实际上超出了屏幕高度，所以左上角是背景灰，这个我后续会优化下，应该是去当前展示部分的左上角一个像素的颜色值。

谢谢了，注意头发（
