### ISSUE TITLE
Easylist啟用時Fanboy's Annoyances 沒有效果 (只有Via瀏覽器才會這樣)

### ISSUE THREAD

**Issue by cbwee** [tuyafeng/Via#711]
在Via瀏覽器中同時訂閱並啟用Easylist和Fanboy's Annoyances這兩個篩選條件時，Fanboy's Annoyances會沒有效果(在 kknews.cc 的下方社交按鈕不會被隱藏)，停用Easylist後這些按鈕就可以成功被隱藏。

我已經用Kiwi Browser + uBlock Origin和Firefox Android+ uBlock Origin試過，這兩個瀏覽器用uBlock Origin同時訂閱這兩個篩選條件也沒有問題，只有Via瀏覽器才會出現這樣的問題。

**Comment by tuyafeng** [comment]
可能是出现了规则冲突，Via 不会做规则的去重，这会导致重复的规则也被加载到内存中，而使得一些规则因关键字被重复规则占用而无法被加载。解决这个问题的办法就是，尽量保证订阅的规则中不包含重复的规则。

**Comment by CB-wee** [comment]
@tuyafeng 請問Via在未來有可能加入自動去除重複規則的功能嗎?

我需要使用 Fanboy's Annoyances，因為這個問題我現在不能訂閱Easylist，只能使用CJX's EasyList Lite代替。

**Comment by tuyafeng** [comment]
规则去重会导致加载规则的过程变得极慢，暂时不会考虑。

**Comment by cbwee** [comment]
> 规则去重会导致加载规则的过程变得极慢，暂时不会考虑。

謝謝，我知道了，所以我先 close issue。
