### ISSUE TITLE
Bug/Issue: No markers are exported

### ISSUE THREAD

**Issue by gdroidaan** [tuyafeng/Via#716]
After commanding (spanish installed, so maybe my words are different)
"Settings > General > Import/Export markers > Export markers"
nothing happens. I waited a few hours, but no popup message appears and no markers file is created. I have almost 1100 markers.

I would much appreciate if you can take a look at this.

**Comment by xiaoxuan010** [comment]
Maybe you refer to "bookmark"(in English) or "Favoritos del navegador" (in Spanish)?
When I try to export bookmarks, I go to (Settings > Gernal > Import/Export bookmarks > Export bookmarks). Then a page of system's file explorer was provide (see picture1). 
![Screenshot_2021-01-31-23-46-49-336_com cxinventor file explorer](https://user-images.githubusercontent.com/58388568/106389665-797e0d80-641f-11eb-86ac-2dbb37f4bfee.jpg)
Then I choose a path and the bookmarks were exported as a html file.(picture 2)
![IMG_20210131_234811](https://user-images.githubusercontent.com/58388568/106389674-83077580-641f-11eb-9798-7f6f8ad4ab4b.jpg)
I think you can try to check you file manager of system file manager. What's more, try to upload more information about your problem (like logs of the app&system)
Hope to be helpful to you!

**Comment by gdroidaan** [comment]
Thank you for you answer! Yes, the process is that, but what I see is something different. I tried It on 3 different mobiles to give you more detail. They are Samsung A5 (android 8.0.0), Samsung A31 (10) and virtual device VMOS (5.1.1). The A31 exports successfully. The A5/VMOS do not. I switched languages to English (US).

PROCESS OK (A31):
1) I go to (Settings > General > Import/Export bookmarks > Export bookmarks).
A short menu window appears. It has 3 lines of text:
-------------------------------
Import/Export bookmarks
Export bookmarks
Import bookmarks
-------------------------------
2) I ckick "Export bookmarks".
It appears a message window saying:
-------------------------------
Message
Bookmarks exported to /sdcard/Download/Via_Bookmarksexport_20210202.html
OK
-------------------------------
3) I press OK. Close the (Settings > General) menu, close Via. I browse the folders and the bookmarks file is ok!

PROCESS NOT OK (A5/VMOS)
1) Same as before.
2) I click "Export bookmarks". The short menu window closes immediately. Nothing more happens. Screen stays in the (Settings > General) menu. I wait but nothing more happens. No bookmark file is created.

That is what I see. When I first write the issue, I though that the process didn't succeed on the A5 because I have almost 1100 bookmarks there. But now I see It is not related to that high number of bookmars. If you need any more data, please tell me. Thanks again!

**Comment by tuyafeng** [comment]
The current 4.1.6 version has fixed this problem, thank you for your feedback.
