### ISSUE TITLE
Need help blocking youtube ads in Via.

### ISSUE THREAD

**Issue by dajpoints** [tuyafeng/Via#719]
https://i.imgur.com/2rNaDcN.png
https://i.imgur.com/xKOtWY9.png
https://i.imgur.com/3gTYujz.png
https://i.imgur.com/gsDGTln.png

Anyone figure out a way to block all of these youtube ads that appear when I search for a video, before the video plays, or under the video?  Is there a script? or ad blocker file I can add that will get rid of them?

**Comment by dajpoints** [comment]
This filter list deletes youtube ads that appear at the start of or during a video:
https://easylist-downloads.adblockplus.org/easylist-minified.txt

Still trying to find a way to get rid of the ads that appear in the youtube search results, under a video, and will get rid of the Youtube TV ad that appears every time I click on a search result within youtube (Clicking "No Thanks" only makes it go away temporarily)..

**Comment by dajpoints** [comment]
Today no ads have appeared in youtube in Via Browser. Just using the same filter list above (easylist minified).  Not sure if the developer of Via Browser did something on the backend or if the filter list is doing it. Hopefully it stays that way.

**Comment by tuyafeng** [comment]
Sometimes if you change the filter list for ad blocking, it may not take effect immediately for some unknown reason, you can restart Via.
