### ISSUE TITLE
能否给via浏览器内置二维码扫描的功能？

### ISSUE THREAD

**Issue by hisenyiu2015** [tuyafeng/Via#720]
开发者你好！能否给via浏览器内置二维码扫描的功能？感觉via浏览器已经很接近完美了，功能够用又不会臃肿，唯一欠缺的就是二维码扫描功能

**Comment by Lowae** [comment]
+1，二维码还是很重要的，免得需要扫二维码还要换个浏览器

**Comment by WuJunkai2004** [comment]
个人感觉二维码其实不太必要，扫二维码用微信就可以了。
而且二维码处理的代码还挺复杂的

**Comment by tuyafeng** [comment]
扫码的工具够多了，暂时不太考虑（
