### ISSUE TITLE
地址栏下拉提示菜单内容的建议

### ISSUE THREAD

**Issue by BenSYZ** [tuyafeng/Via#721]
在地址栏中输入部分域名会有下拉提示补全。但是提示菜单补全个人觉得有一点问题，貌似是把最新的输入历史放在最下面，导致看不到最新的历史，建议是倒序。其次建议首选的补全是域名补全，不要补全到url。只是个人建议，如果您觉得不合适，请见谅。

ps. 收藏夹貌似也是最新的在最下面，这个可能各有各的习惯吧。在最下面貌似也没问题，只是多嘴一句: )

**Comment by tuyafeng** [comment]
确实是时间顺序，这个之后的版本会修改，确实应该是最新的最靠近地址栏才对。

**Comment by tuyafeng** [comment]
4.2.1 已经解决了这个问题，目前最近的记录会最靠近地址栏。
