### ISSUE TITLE
Sometimes via doesn't open the URL requested via intent 

### ISSUE THREAD

**Issue by ronnac** [tuyafeng/Via#722]
Sometimes Via doesn't open the URL requested via intent, but another URL that was opened in a previous session. However I can find the requested URL listed on top of the History menu.
This happens when I don't use Via for a while, e.g. the first use in the morning. I have disabled battery optimization for Via to make sure it isn't put to sleep by the OS.

**Comment by tuyafeng** [comment]
In the latest version 4.1.7, I refactored the entire tab management logic. This bug should no longer exist, you can update and try.

**Comment by ronnac** [comment]
That would be great! On play store it's still v4.1.6. I'll wait a few days. Thank you! 
-------- Original message --------From: Yafeng <notifications@github.com> Date: 06/02/21  06:15  (GMT+01:00) To: tuyafeng/Via <Via@noreply.github.com> Cc: Nick Römer <nick.romer@skynet.be>, Author <author@noreply.github.com> Subject: Re: [tuyafeng/Via] Sometimes via doesn't open the URL requested via intent  (#722) 
In the latest version 4.1.7, I refactored the entire tab management logic. This bug should no longer exist, you can update and try.

**Comment by ronnac** [comment]
Hi,

Version 4.1.7 still isn't on paly store. Did you mean 4.1.6?
That version, still has the bug.

**Comment by tuyafeng** [comment]
I am trying to reproduce this error. "Always restore tabs" is enabled, and there are indeed tabs that need to be restored. Via is not in the background. I use the intent to start Via to open the link. At this time, the restored tab is in the foreground instead of the intent tab. Is my description correct?

**Comment by ronnac** [comment]
No:
- I have the setting "Don't restore tabs on startup"
- The problem occurs when Via is in the background. I have disabled battery optimisation, which probably also disables sleep mode.
- I use "evie" as launcher, which has a web search field. (I chose google as search engine). I enter my search term in evie, and when I press Enter it uses the default browser (via) to display the search results.
This works most of the time. However, when I let some time pass (1 hour?) without using via and I use this procedure, via shows a different tab (one that was active before). However, in via's browsing history screen, I can see my search results as second oldest item.

**Comment by tuyafeng** [comment]
Did you mean that the intent tab is not active after the call? Or is there no intent tab on the interface, but that link has been opened?

**Comment by ronnac** [comment]
I have to check.

**Comment by ronnac** [comment]
The tab is open but not visible.I am unable to reproduce it consistently,  but you can try:Open 1 or 2 tabs in via.Go to the home screen. Open several heavy apps (YouTube, maps,  a podcast player; ...)Send intent to via
-------- Original message --------From: Yafeng <notifications@github.com> Date: 18/02/21  16:25  (GMT+01:00) To: tuyafeng/Via <Via@noreply.github.com> Cc: Nick Römer <nick.romer@skynet.be>, Author <author@noreply.github.com> Subject: Re: [tuyafeng/Via] Sometimes via doesn't open the URL requested via intent  (#722) 
Did you mean that the intent tab is not active after the call? Or is there no intent tab on the interface, but that link has been opened?

**Comment by tuyafeng** [comment]
OK, I will try the steps you said, try to reproduce and fix it.

**Comment by ronnac** [comment]
Good news! I can reproduce the bug consistently now.- in Android settings/device care/battery click on "optimize now" (might be specific to samsung phones)- open a page via intent in via
-------- Original message --------From: Yafeng <notifications@github.com> Date: 18/02/21  18:53  (GMT+01:00) To: tuyafeng/Via <Via@noreply.github.com> Cc: Nick Römer <nick.romer@skynet.be>, Author <author@noreply.github.com> Subject: Re: [tuyafeng/Via] Sometimes via doesn't open the URL requested via intent  (#722) 
OK, I will try the steps you said, try to reproduce and fix it.

**Comment by tuyafeng** [comment]
The 4.2.1 version improves the intent call, and the problem seems to be solved. Do you still have problems there?

**Comment by ronnac** [comment]
Yes, the bug is fixed, it works! Via is now my default browser. Thank you very much! I just discovered another minor bug: in settings/ general/ restore tabs on startup when I select "restore all tabs" I get a pop up "you've gone incognito. Tabs will not be restored. " even when I'm not in incognito mode.  The restore functionality does work however,  it's only the message that is wrong. 
-------- Original message --------From: Yafeng <notifications@github.com> Date: 25/02/21  06:09  (GMT+01:00) To: tuyafeng/Via <Via@noreply.github.com> Cc: Nick Römer <nick.romer@skynet.be>, Author <author@noreply.github.com> Subject: Re: [tuyafeng/Via] Sometimes via doesn't open the URL requested via intent  (#722) 
The 4.2.1 version improves the intent call, and the problem seems to be solved. Do you still have problems there?

**Comment by tuyafeng** [comment]
OK, i will fix it.
