### ISSUE TITLE
希望可以增加广告过滤规则批量导入和导出

### ISSUE THREAD

**Issue by Jiang10086** [tuyafeng/Via#726]
希望可以增加广告过滤规则批量导入和导出，就和uBlock Origin一样导出为一个txt文本。我自己有写很多规则但是一条条复制上去太麻烦了
Via，超棒的浏览器！

**Comment by tuyafeng** [comment]
可以的，不过你需要一个可以查看 `/sdcard/Android/data` 区的文件管理器，自定义规则的路径在 `/sdcard/Android/data/mark.via/files/filters/custom.txt` 这个文件。
