### ISSUE TITLE
用鼠标第一次点击页面任何地方都会跳转到网页最上面

### ISSUE THREAD

**Issue by fxqy** [tuyafeng/Via#740]
我把via安装到了电视上，接上鼠标，看视频挺方便。
就是有个小问题。用鼠标第一次点击页面任何地方都会跳转到网页最上面，然后网页操作就正常了。
所以我现在进网页就在空白处点一下鼠标左键。
我不知道能不能通过添加脚本
document.body.click();
或者其他脚本来解决这个问题。
也试过安装其他的浏览器，虽然不存在此问题，但用不习惯，求大神能解决下

**Comment by fxqy** [comment]
脚本不行，进页面的第一个左键事件还是跳转到网页最上面

**Comment by tuyafeng** [comment]
奇怪的错误，看起来是网页的焦点错误了？我之后查查看。
