### ISSUE TITLE
恢复上一次会话时能否对非当前网页懒加载

### ISSUE THREAD

**Issue by 14725** [tuyafeng/Via#743]
（尤其当页面过多时），启动时恢复未关闭标签，浏览器同时加载所有标签导致浏览器卡死。

如果可能，希望这些“恢复”的标签仅仅在显示的时候再加载。

（说不定对 https://github.com/tuyafeng/Via/issues/545 有帮助）

**Comment by 14725** [comment]
https://github.com/tuyafeng/Via/issues/727 的副本
抱歉。

**Comment by 14725** [comment]
关闭这个请求。

**Comment by 14725** [comment]
求关闭。这是 https://github.com/tuyafeng/Via/issues/727 的副本

**Comment by 14725** [comment]
啊啊啊啊，为什么我关不掉这个issue啊啊啊😱

**Comment by tuyafeng** [comment]
新版本 4.2.1 中已经添加该特性。
