### ISSUE TITLE
自定义主页添加书签

### ISSUE THREAD

**Issue by WuJunkai2004** [tuyafeng/Via#747]
应如何编写自己的自定义主页里面的代码，使得可以在添加书签时添加到主页上？

**Comment by tuyafeng** [comment]
自定义主页目前都无法获取书签数据，可以考虑使用网页本身的持久化存储方式比如 local storage 处理。

**Comment by WuJunkai2004** [comment]
能否由via来提供一套标准，使自定义主页可以拥有更多的功能？
比如规定自定义主页存放的路径，主页书签的ClassName,logo的ClassName

**Comment by tuyafeng** [comment]
就目前来看，本地主页存在的问题很多，同时 android 也在收窄文件权限，所以暂时不考虑。
