### ISSUE TITLE
Desktop Site View

### ISSUE THREAD

**Issue by kairusds** [tuyafeng/Via#754]
Turning on desktop site or setting my user-agent to Chrome (PC) doesn't seem to work and this bug has been happening since June of 2020.

**Comment by tuyafeng** [comment]
Can you provide the requested desktop view site you visited?

**Comment by kairusds** [comment]
> Can you provide the requested desktop view site you visited?

nevermind it was my bad, i had a script that was forcing the viewport everytime i visit a site
