### ISSUE TITLE
[Request]Import/Export app settings to a local file

### ISSUE THREAD

**Issue by Mitia99** [tuyafeng/Via#756]
Dear dev,

It will be great to have an import/export feature for app setting in order to do quick settings tweak backup when using 2 or more device.

Thanks,

**Comment by tuyafeng** [comment]
Currently the data you export contains bookmarks, scripts, advertising rules and settings.

**Comment by Mitia99** [comment]
@tuyafeng Thank you, I didin't know that it was already available.I'll close this issue then.
