### ISSUE TITLE
[Bug]在搜索栏搜索内容概率卡死

### ISSUE THREAD

**Issue by AyakaAgo** [tuyafeng/Via#761]
![Screenshot_2021-02-25-16-48-00-361_mark via](https://user-images.githubusercontent.com/20831549/109127762-bec8fd00-7789-11eb-86dc-867b489254ee.jpg)

App Version: 4.2.1(20210222)

**Comment by DOGE-tt** [comment]
此

**Comment by DOGE-tt** [comment]
可以试试打开 https://gitee.com/openharmony/docs/blob/master/zh-cn/figures/1.png，长按查看图片，会开一个 base64 的新标签页，然后在地址栏输入 base，查看是否会卡住

在模拟器这样会卡一会儿，但不会无响应

不过这可能是平台问题？

**Comment by tuyafeng** [comment]
终于找到原因了！！！事情是这样的，在浏览过程中，可能有些网站会偏好用 base64 的图片，即使图片非常大，这样数据库中可能存在一条几百 K 的链接地址，到目前为止这还是正常的。可是把这条几百 K 的 string 设置到界面时，textview 不会截断 string，所以导致了卡死。感谢你的反馈。在 4.2.9 版本中会修复这个错误。
