### ISSUE TITLE
Via瀏覽器 打開 https://en.miui.com/v12_5 以後每次都閃退

### ISSUE THREAD

**Issue by cbwee** [tuyafeng/Via#765]
Google Play版 Via瀏覽器 4.2.1, 只要一打開英文版 MIUI 12.5 網站 https://en.miui.com/v12_5 ，就會閃退，試過很多次了。

我也使用其他瀏覽器測試過，包括使用WebView的ADM Browser，和ES瀏覽器，只有Via才會閃退。

**Comment by cbwee** [comment]
@tuyafeng 我在經過很多次測試和調整設定以後找到造成問題的原因了。

我在兩台手機上使用完全一樣的Via設定資料，Android 7.1 和 Android 10，但是只有 Android 10 上出現這個問題，所以我開始在 Android 10 手機上調整設定。

最後我發現如果在Via中使用自訂 user agent ，在打開一些網站時就會閃退，只有使用預設 user agent 時才不會閃退。

但是這個閃退的問題是在更新到 Via 4.2.1 以後才出現的，以前使用Via瀏覽器也是自訂 user agent 都沒有閃退的問題。

**Comment by cbwee** [comment]
我剛才繼續測試以後，發現雖然在 Android 10 中Via瀏覽器使用自訂 user agent 會出現問題，但是我把這個 user agent 拿去HTML Stripper網站移除格式以後，再放回去Via瀏覽器使用，就沒有再出現閃退的問題了。

**Comment by tuyafeng** [comment]
看起来是复制的 user agent 不是纯文本的原因，下个版本会解决。
