### ISSUE TITLE
Google the pages translation engine no longer works on Android 4.4.2 How can I report this malfunction to Google?

### ISSUE THREAD

**Issue by AlbahrawyTiger** [tuyafeng/Via#767]
Hello friends, how can I notify Google that the pages translation engine has crashed on Android 4.4.2 ?, Via browser is working fine, but the pages translation engine is no longer working

**Comment by tuyafeng** [comment]
Are you sure that all website translations fail to take effect? Some sites with cross-domain restrictions, such as GitHub, cannot use translation.

**Comment by AlbahrawyTiger** [comment]
Yes, the translation engine does not work on all websites.
I am sure of that and I know that some domains cannot use translation.
This problem has existed for more than two months on Android 4.4.2, starting with Android 5 the translation engine works well.
-Can you help?

**Comment by AlbahrawyTiger** [comment]
@tuyafeng Can you help?

**Comment by tuyafeng** [comment]
This issue has been fixed, I will close it.
