### ISSUE TITLE
橫向顯示時，下方沒有退出按鈕 / 分頁還原的問題

### ISSUE THREAD

**Issue by cbwee** [tuyafeng/Via#773]
1. 橫向顯示時，下方沒有退出按鈕

手機如果切換到橫向顯示使用Via，按下選單按鈕後，下方本來應該要出現的退出按鈕不會顯示。
![Screenshot_2021-03-03-07-47-16-003_mark via gp](https://user-images.githubusercontent.com/34395942/109731118-a75c9a80-7bf5-11eb-8062-3c948631a26b.jpg)

2. 分頁還原的問題

VIa 目前分頁還原只能選擇，停用、一律，或是先詢問。

但是我希望能再增加一個選項，沒有按下退出按鈕以前一律還原分頁。

因為我在使用時，有時候Via會因為系統RAM不夠被關閉，這樣我就遺失了已經打開的分頁。
所以我需要自動還原分頁。
但是我希望在按下退出按鈕後，所有的分頁可以完全被關閉 (下次使用時不還原)。

所以我需要這個選項，才能像其他瀏覽器一樣，即使RAM不夠被系統關閉，再次開啟時能自動還原分頁，只有手動按下退出按鈕後，下次開啟才不還原分頁。

**Comment by tuyafeng** [comment]
4.2.4 版本中，已经加强了标签恢复功能，当应用遭到误杀时，总是会恢复你的浏览页面（包括当前浏览页的进度，前进后退栈），同时，所有的标签恢复都是懒加载的，永远只会加载你当前浏览的页面。

**Comment by cbwee** [comment]
@tuyafeng 我還是希望可以再增加一個選項，或是在Via被手動強制關閉 (沒有使用退出按鈕時) 保留頁面。

因為我在切換到其他app時，有時候會在切換的畫面不小心手滑把Via滑掉，這樣再回到Via，之前瀏覽的頁面也沒了。
