### ISSUE TITLE
将书签移动到文件夹后书签列表显示错误

### ISSUE THREAD

**Issue by a563501734** [tuyafeng/Via#805]
今天批量导入书签后想整理下发现的，书签文件夹只能有一层，，，将书签移动到某个文件夹或删除某个文件夹后列表就乱了，删除某项时实际上删除的是其他书签

另外希望为脚本添加更多的API如管理书签、设置、代理等

**Comment by tuyafeng** [comment]
书签已经重构了，最近几天就会发版，敬请期待。

**Comment by tuyafeng** [comment]
书签重构后的版本已经发布了，4.2.4 之后的版本都默认启用了新的书签页。
