### ISSUE TITLE
支持外部下载 app

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [tuyafeng/Via#812]
在碰上某些文件（如大型 apk）的时候这个功能可以让浏览器提供一个界面，让用户选择用 ADM、Download Navi 这类程序下载，Firefox 就提供了这个选项。

**Comment by Mitia99** [comment]
@KrasnayaPloshchad Feature already available

Settings>General>Download manager

**Comment by KrasnayaPloshchad** [comment]
🤝
