### ISSUE TITLE
支持小书签

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [tuyafeng/Via#815]
如果 Via 浏览器能支持 javascript: 开头的书签，那么像这些站点提供的小书签就都能派上用场。
https://ctrlq.org/ios/?qr
https://wantora.github.io/qrcode-bookmarklet/
https://www.addtoany.com/users/bookmarklet
https://www.shareaholic.com/tools/bookmarklet/

**Comment by tuyafeng** [comment]
4.2.4 版本时，Via 重构了书签页面，初衷是为了更好的书签管理体验，但也意外地支持了你提到的特性，可以试试看。

**Comment by tuyafeng** [comment]
4.2.8 加强了小书签的部分，现在应该正常了。
