### ISSUE TITLE
疑似下载列表中项目过多时会导致via读取无响应

### ISSUE THREAD

**Issue by bot74** [tuyafeng/Via#816]
![bug1](https://user-images.githubusercontent.com/41332266/113657774-3f581300-96d1-11eb-883c-da41a37675e7.jpg)
![bug2](https://user-images.githubusercontent.com/41332266/113657783-42eb9a00-96d1-11eb-8673-622788cca1bd.jpg)

遇到一些低分辨率表情包时会经常保存，所以下载列表里有很多既往的下载历史，导致整个列表很长，打开时直接不响应。4.0.1版本没有这个情况，今天更新到4.2.6以后出现的。

Debug信息：
Phone: HONOR COL-TL10(COL-TL10)
App Version: 4.2.6(20210331)
Snapshot Time: 2021-04-06 12:06:26
CPU ABI: arm64-v8a 
Screen: 1460x720
Android Version: 9 API28
Language: zh-CN
WebView Impl: com.google.android.webview
WebView Version: 74.0.3729.157(372915750)

希望能有帮助

**Comment by tuyafeng** [comment]
看来还是应该做个异步加载🤔

之前因为发现异步加载列表，线程切换的时间远超过了加载列表的时间，所以是同步处理的，现在看来还是需要放在异步去填充列表。感谢你的反馈。

**Comment by tuyafeng** [comment]
这个错误在 4.2.8 版本已经得到了修复。
