### ISSUE TITLE
地址栏设定为显示url时，url中的中文字符无法被显示为中文

### ISSUE THREAD

**Issue by yige233** [tuyafeng/Via#822]
例如，我在打开链接[http://github.com/search?q=浏览器](http://github.com/search?q=浏览器)后，地址栏中会显示为[https://github.com/search?q=%E6%B5%8F%E8%A7%88%E5%99%A8](https://github.com/search?q=%E6%B5%8F%E8%A7%88%E5%99%A8)，而不是带中文字符的url。我在Chrome上打开同样的链接，地址栏中可以显示为中文，复制链接时则是复制编码后的链接（不是很确定应该叫啥，uri？）。希望能显示为中文吧，视觉效果上来看链接整洁很多，要是能像pc上，复制部分链接时可以把中文保留，复制全部链接时再复制为编码后的链接就更好了。

**Comment by 14725** [comment]
另外，有否选项可在输入URL（含中文）后自动编码回百分号编码而不是触发搜索？如果尝试修改get的提交参数这会有用。

（如果这会引起麻烦，那么我道歉。）
