### ISSUE TITLE
手势方面，用户体验改进

### ISSUE THREAD

**Issue by kebinzhi** [tuyafeng/Via#825]
1、现在很多手机都是全面屏手势了，很多都有一个手势 >> 边缘往屏幕中间滑动后退一步。
2、第1点导致了via现在的前进后退手势有很多情况会和全面屏手势冲突，导致成功率下降。且不好掌握滑动起点。实测关掉全面屏手势，成功率大幅上升。

优化建议：
1、参考夸克之类，**只要在屏幕上左滑/右滑就能触发**前进后退手势，不用从边缘滑动。
2、参考夸克/微博/微信之类，当处于**页面顶部时，有下拉手势**，提供刷新网页功能。

**Comment by tuyafeng** [comment]
现在其实已经是滑动屏幕前进后退了，抱歉文案给你带来的误导。现在在 Via 应用当中，不止是网页，设置页面一样可以滑动返回。

**Comment by kebinzhi** [comment]
并没有，滑动屏幕中间没反应。



---Original---
From: ***@***.***&gt;
Sent at: 2021年4月30日(Fri) PM4:08
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tuyafeng/Via] 手势方面，用户体验改进 (#825)




 
现在其实已经是滑动屏幕前进后退了，抱歉文案给你带来的误导。现在在 Via 应用当中，不止是网页，设置页面一样可以滑动返回。

**Comment by tuyafeng** [comment]
如果你那边不是，请检查应用版本，最新的版本是 4.2.7，4.x 之后的版本应该都是可以正常滑动屏幕前进后退的。

**Comment by kebinzhi** [comment]
最新版，有很大概率手势没用。极小概率生效。



---Original---
From: ***@***.***&gt;
Sent at: 2021年4月30日(Fri) Evening8:10
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tuyafeng/Via] 手势方面，用户体验改进 (#825)




 
如果你那边不是，请检查应用版本，最新的版本是 4.2.7，4.x 之后的版本应该都是可以正常滑动屏幕前进后退的。
