### ISSUE TITLE
[Privacy] Via should opt-out from WebView statistics collection

### ISSUE THREAD

**Issue by Fs00** [tuyafeng/Via#827]
Today I've peeked into the manifest file of your app (nice job btw) and I've found out that it does not opt-out from WebView statistics collection by Google.
To do that, you need to simply add a meta-data tag inside your AndroidManifest.xml (see https://developer.android.com/guide/webapps/webview-privacy#opt-out).
This small change would make the browser a bit more privacy-oriented by default. After all, Google already collects enough data from our phones. :)

Thank you!

**Comment by tuyafeng** [comment]
Thank you very much for your correction, I will add this change in the future version.

**Comment by Fs00** [comment]
I see that this has been implemented in the latest version. Thank you!
