### ISSUE TITLE
[Bug Via 4.2.8]No search suggestions on global version

### ISSUE THREAD

**Issue by Mitia99** [tuyafeng/Via#848]
Dear dev,

Search suggestions are not working on global(playstore) via version.

Thanks for investigating,

Request reference: #100![Via browser global version_no search suggestions.jpg](https://user-images.githubusercontent.com/56766778/118356619-6c240380-b576-11eb-9a8f-97e93452fb27.jpg)

**Comment by akg27th** [comment]
Yes, this is really an unfair issue in Global via browser version.

**Comment by malekairmaroc7** [comment]
Any updates on this? If this feature is going to be added then I will use Via as main browser

**Comment by tuyafeng** [comment]
The feature of the search suggestions is planned.

**Comment by nikolastoshic** [comment]
> The feature of the search suggestions is planned.

I hope soon.

**Comment by nikolastoshic** [comment]
> Dear dev,
> 
> Search suggestions are not working on global(playstore) via version.
> 
> Thanks for investigating,
> 
> Request reference: #100![Via browser global version_no search suggestions.jpg](https://user-images.githubusercontent.com/56766778/118356619-6c240380-b576-11eb-9a8f-97e93452fb27.jpg)

Is there a fix yet? So annoying. 😩

**Comment by tuyafeng** [comment]
Version 4.4.6 supports selecting the source of search suggestions.
