### ISSUE TITLE
[Feature request] Extension support

### ISSUE THREAD

**Issue by akg27th** [tuyafeng/Via#849]
Sir, kindly give the feature of via browser with extension support and please make via browser chromium based browser.
And also i never wants to change from via browser to kiwi or any other browser to use extension.
I love this browser and wanted to stay forever.

**Comment by akg27th** [comment]
This browser needs a very powerful AdBlocker.
Because filter list aren't enough to block all the Ads.😞😩

**Comment by akg27th** [comment]
This browser needs a very powerful AdBlocker.
Because filter list aren't enough to block all the Ads.😞😩

**Comment by tuyafeng** [comment]
The filter list is powerful enough.
