### ISSUE TITLE
在电视上面安装Via，能安装，也能打开，就是没法控制，也不显示鼠标。

### ISSUE THREAD

**Issue by qq1056123185** [tuyafeng/Via#853]
在电视上面安装Via，能安装，也能打开，就是没法控制，也不显示鼠标。
我看别人发的帖子，上面都是可以显示鼠标的啊，我的电视怎么不显示鼠标。

**Comment by zmyjs** [comment]
因为你没插键盘，需要买个无线或者蓝牙键盘（键鼠一体）

**Comment by tuyafeng** [comment]
随便买个蓝牙键盘鼠标啥的应该就行。
