### ISSUE TITLE
[Feature Request] Add an option to send GPC signal

### ISSUE THREAD

**Issue by cbwee** [tuyafeng/Via#856]
Via can only send Do Not Track signal, I hope an option for sending GPC signal can also be added.

[Global Privacy Control (GPC)](https://globalprivacycontrol.github.io/gpc-spec/)
[Test page](https://tools.browsernative.com/)

**Comment by tuyafeng** [comment]
Wait until Global Privacy Control (GPC) becomes an official agreement.
