### ISSUE TITLE
夜间模式问题

### ISSUE THREAD

**Issue by Taivasjumala** [tuyafeng/Via#859]
在浏览器启动的情况下，系统暗黑模式打开，退出浏览器，关闭系统暗黑模式，重进浏览器，部分元素仍停留在夜间模式，启动夜间模式再关闭恢复正常。
![Screenshot_2021-06-03-10-15-19-034_mark via](https://user-images.githubusercontent.com/72904966/120575980-9d487300-c454-11eb-8e5c-786030e12afc.jpg)

**Comment by tuyafeng** [comment]
之后会修复。
