### ISSUE TITLE
Google.com looks outdated on Via

### ISSUE THREAD

**Issue by K1DV5** [tuyafeng/Via#870]
I thought via uses webview which should be about the same as chrome. But the site looks like this on Via.

![Screenshot_20210616-093705](https://user-images.githubusercontent.com/40162008/122252624-2db29900-ced4-11eb-8a59-d53513a6b1c1.jpg)

And here's how it looks on Chrome.

![Screenshot_20210616-093638](https://user-images.githubusercontent.com/40162008/122252748-415dff80-ced4-11eb-9209-72dc85624fa1.jpg)

I tried to play with the user agent, even copied the user agent of chrome and pasted it as a custom one in Via, but it didn't work.

**Comment by K1DV5** [comment]
I just noticed that the page looks ok after clearing the cookies. But a subsequent reload or any page loads restore the problem.

**Comment by Krishna-verma** [comment]
I failed to recreate your issue. Are you sure this is happening with default settings? Can you share the exact URL of that webpage.

**Comment by K1DV5** [comment]
Sorry, I had disabled JavaScript. When I enabled it, it looks ok. But why is it different based on whether JavaScript is enabled?

**Comment by K1DV5** [comment]
Closing anyway because it's not related to this browser.
