### ISSUE TITLE
如果集成多个索引，再加一个扫码就完美了

### ISSUE THREAD

**Issue by aheig** [tuyafeng/Via#872]
如题：
        如果集成多个索引，再加一个扫码就完美了。因为现在很多时候电脑浏览到一个非常好的网站，想及时收藏到手机浏览器，直接打开手机浏览器扫码是最方便的

**Comment by Taswen** [comment]
此issue可以终结了
见 README 
![image](https://user-images.githubusercontent.com/30777327/123771123-63f10f00-d8fd-11eb-81bf-94543997a5d0.png)

**Comment by tuyafeng** [comment]
请使用手机相机等自带应用扫描。
