### ISSUE TITLE
add more language

### ISSUE THREAD

**Issue by tsouvaa** [tuyafeng/Via#876]
![Screenshot_2021-06-19-19-44-02-786_mark via](https://user-images.githubusercontent.com/46875253/122643269-1d4f2800-d139-11eb-8aed-45c8073d6282.png)

hi sir,
please the developer add all languages ​​in the application via, when i translate the website, my language is not available, (indonesian). and for other languages ​​also equally' its very annoying.

**Comment by malekairmaroc7** [comment]
Is this not a Google Translator issue?

**Comment by tuyafeng** [comment]
I solved this problem in version 4.3.0, please wait patiently for the review by Google play.
