### ISSUE TITLE
希望能多增加一些键盘快捷键，以及浏览器快捷键和系统冲突。

### ISSUE THREAD

**Issue by whoarethey** [tuyafeng/Via#879]
使用平板浏览网页时，用键盘操作很方便，测试了很多浏览器只有via键盘快捷键做的最好。但还能添加一些方便的快捷键，比如加入展开标签页的快捷键，上下半屏的快捷键一次滑动半屏，比使用上下左右键快很多。如果能集成类似于Vimium C 插件，使用vim全键盘操作就更好了。快捷键同系统冲突应该是国内厂商魔改系统导致的问题，在其它手机测试没这个问题。我的系统CTRL+w是关闭应用与via的关闭标签页冲突了，希望修改自定义键盘快捷键或者在使用via时屏蔽掉与系统冲突快捷键。

**Comment by tuyafeng** [comment]
空格不就可以实现划屏吗？目前 Via 是空格滑动一屏的 3/4，空格是往下，shift + 空格是往上。Vim 插件太 geek 了，目前不考虑。键盘操作快捷键这个目前也无法获取系统映射的值，所以也无法解决冲突。至于自定义快捷键，这个主要是考虑到学习成本，还是选择跟 Chrome 对齐，再考虑到现在的平板键盘用户，我觉得起码目前来说意义不大。
