### ISSUE TITLE
[Feature] Add sliding events to specific buttons | 添加滑动事件到特定的按钮

### ISSUE THREAD

**Issue by Taswen** [tuyafeng/Via#881]
现在滑动事件是针对工具栏整体的，可对应前进、后退或是其他。但实际上可以针对不同的按钮添加不同操作。例如按住home键滑动可以是网页的前进后退，而按住标签按钮则可以是标签页的轮换。

在实现上，由于每次滑动都需要按住某个地方，可以在取得所按按键之后执行对应操作。

Now the sliding event is for the whole the toolbar, which can be correspond to forward, backward or other. However, different operations can be connected to different buttons. For example, holding the `Home` button to slide can be mapped to going forward or backward of the webpage, and holding the `Tab` button can be mapped to switch the tab page.

In implementations, since each slide operation needs to press somewhere, the relevant operation can be performed after obtaining the pressed button.

**Comment by tuyafeng** [comment]
滑动操作本身是一个相对轻松的手势，对比点击来说，滑动不需要非常精准的热区，这让滑动操作优雅且十分适合移动端。而一旦为了增加快捷操作而丢掉滑动不需要精准控制起点的优点，我觉得是难以接受的，所以不考虑。
