### ISSUE TITLE
添加了ublock origin规则 ，打开YOUTUBE还是有广告

### ISSUE THREAD

**Issue by C-HR** [tuyafeng/Via#885]
手机安装的有FIREFOX浏览器，安装了ublock origin，youtube无广告，
我在VIA里面也添加了ublock origin同样规则 ，打开YOUTUBE还是有广告，请问怎么回事呢？
谢谢

**Comment by tuyafeng** [comment]
ublock 用的是自己私有的规则格式吧？

**Comment by dajlelion** [comment]
You can add this to Settings > General > Ad Blocking > Filter Subscriptions:
https://raw.githubusercontent.com/dajlelion/test/main/filters.txt

It blocks all ads on youtube including the overlay video ads. I'll update it if I see an ad again but so far it's been working good. It only has 86 lines.

**Comment by tuyafeng** [comment]
> You can add this to Settings > General > Ad Blocking > Filter Subscriptions: https://raw.githubusercontent.com/dajlelion/test/main/filters.txt
> 
> It blocks all ads on youtube including the overlay video ads. I'll update it if I see an ad again but so far it's been working good.

Nice. Thank you so much.
