### ISSUE TITLE
Can via save text file from website?

### ISSUE THREAD

**Issue by sym233** [tuyafeng/Via#889]
For example, http://example.com/text.txt 
How to download this file?

**Comment by 14725** [comment]
What if we have only the URL in text but no link in <A>? 

On PC, I could simply open it and Ctrl+S, what if I use Via?

**Comment by Exanoff12** [comment]
If the file exists in the backend it will be ripped by httrack. If the file doesn’t even have a url then its inaccessible.

**Comment by 14725** [comment]
I'm so sorry...
Sometimes I get an URL but no <a> LINK to it. 
For example how do I download 
```
https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
```
without something else? This URL above is not clickable ( though accessable and giving me only text not a file when accessed) , and a bruh click won't give me a Download.
