### ISSUE TITLE
在浏览器全屏时给出提示。

### ISSUE THREAD

**Issue by 14725** [tuyafeng/Via#906]
全屏模式可以用来钓鱼。

请检查 https://feross.org/html5-fullscreen-api-attack/ 

如果有人试图搞类似的恶作剧，那么给一个“已进入全屏模式”的提示会很有用。

**Comment by tuyafeng** [comment]
感谢你提出如此好的问题，我会在之后的版本中加入全屏模式的相关提示。

**Comment by tuyafeng** [comment]
4.3.1 已添加相应提示。
