### ISSUE TITLE
如何把网页添加到手机桌面？

### ISSUE THREAD

**Issue by someone-TJ** [tuyafeng/Via#913]
如何把网页添加到手机桌面？

**Comment by undefined303** [comment]
更新新版本

**Comment by someone-TJ** [comment]
最新的版本4.3.0也没找到这个功能

**Comment by someone-TJ** [comment]
> 更新新版本

最新的版本4.3.0也没找到这个功能

**Comment by undefined303** [comment]
长按添加书签就有了

**Comment by undefined303** [comment]
4.3.1了，更新一下吧

**Comment by someone-TJ** [comment]
> 4.3.1了，更新一下吧

没找到apk，哈哈，能发一个下载链接吗

**Comment by undefined303** [comment]
> > 4.3.1了，更新一下吧
> 
> 没找到apk，哈哈，能发一个下载链接吗

官网已经是4.3.1了（或者酷安）https://viayoo.com/zh-cn/

**Comment by someone-TJ** [comment]
更新了，长按哪里，链接吗，在书签里面长按链接弹出的菜单项有一个add to homepage，但是那是添加到浏览器主页，不是添加到手机桌面

**Comment by undefined303** [comment]
> 更新了，长按哪里，链接吗，在书签里面长按链接弹出的菜单项有一个add to homepage，但是那是添加到浏览器主页，不是添加到手机桌面

添加书签

**Comment by undefined303** [comment]
![Screenshot_20210831_082002_mark via](https://user-images.githubusercontent.com/54739035/131422088-58d89163-4eb8-4679-beeb-e2348e35e029.jpg)

**Comment by tuyafeng** [comment]
4.3.1 之后已经实现了这个功能，长按主菜单中的添加书签即可。
