### ISSUE TITLE
Can't download anything

### ISSUE THREAD

**Issue by Zakaria-ouertani** [tuyafeng/Via#920]
Anytime I try do download stuff it shows this 
 #![Screenshot_20210829-141159](https://user-images.githubusercontent.com/75418838/131251579-a82d76d0-679e-4040-b19e-0a1cc6e78197.png)

Device : Nokia 2.3
Android 11 
Not rooted

It doesn't ask for storage permissions and when i grant it from settings it says media only access

**Comment by Clashkid155** [comment]
Think it's something relating to scoped storage in android 11

**Comment by Zakaria-ouertani** [comment]
> Think it's something relating to scoped storage in android 11

After a few more downloads I noticed that some work while others don't

As an example I can't downlad from github
