### ISSUE TITLE
Manually arrange the icon/link on homepage by dragging.

### ISSUE THREAD

**Issue by wrenashe** [tuyafeng/Via#923]
Manually arrange the icon/link on the homepage by dragging.

**Comment by undefined303** [comment]
> Manually arrange the icon/link on the homepage by dragging.

It's supported by the browser.First,long press one of the icons.Then it will show an edit box,long press the icon in it,and drag to arrange it.

**Comment by wrenashe** [comment]
In my app(4.2.6/20210331), when I press the icon in homepage long enough, there is a context menu pops up, and there is no more response if I continue long press the icon. Am I wrong?

**Comment by wrenashe** [comment]
I got it works from the latest version. Thanks. 4.3.1(20210829)

**Comment by undefined303** [comment]
> In my app(4.2.6/20210331), when I press the icon in homepage long enough, there is a context menu pops up, and there is no more response if I continue long press the icon. Am I wrong?

I downloaded v-4.2.6 just now.Press the icon for about 0.5 seconds and drag it is enough.It will be too late when you see the context menu.The latest version is just like what I said before.

**Comment by wrenashe** [comment]
Thanks for this additional hint.
