### ISSUE TITLE
［新功能］自定义规则支持正则或通配符

### ISSUE THREAD

**Issue by jeeeet** [tuyafeng/Via#926]
现在好多网站广告都是js生成随机class和id, 什么时候能支持正则或者通配符啊, 此需求非常大

**Comment by undefined303** [comment]
注意看帮助，支持通配符
![Uploading Screenshot_20210907_103552_mark.via.jpg…]()

**Comment by tuyafeng** [comment]
广告拦截是支持通配符的，但是正则不支持。正则规则在 abp 的比重非常小，而实现完整正则匹配需要牺牲更多性能，所以不考虑实现 abp 的正则规则支持。
