### ISSUE TITLE
打开via后快速点击地址栏产生多个叠加层

### ISSUE THREAD

**Issue by Young-Lord** [tuyafeng/Via#937]
此问题主要出现在较旧的手机上，个人使用的小米5和乐2 Pro都出现过
via 4.3.1 酷安下载

https://user-images.githubusercontent.com/51789698/134755492-e846c140-f610-4bce-947c-338ec1c2f492.mp4

**Comment by tuyafeng** [comment]
4.3.2 版本已修复该问题。
