### ISSUE TITLE
Icon to see if an SSL certificate is valid or not?

### ISSUE THREAD

**Issue by shonay** [tuyafeng/Via#939]
Hi there,
Is there an option somewhere in the browser that allows me to see if a website has a valid SSL certificate installed? Like in some other browsers there's usually a green icon saying that it's a protected site, and if I click on it then it tells me what certificate is installed and if it's verified and valid.

I can't seem to find that icon or option anywhere. If you do have it in your app, please let me know where to find it and if not, please can you implement it? Often when I purchase items from websites using my phone browser I make sure the site itself is secure before entering any of my personal details.

Other than that, I really really love what you guys are doing with your browser. It really deserves more recognition! I've set it as my default on my Android.

**Comment by Kita2345** [comment]
Is it possible to add the SHA-256 and SHA-1 to the SSL certification tab info?

**Comment by tuyafeng** [comment]
> Is it possible to add the SHA-256 and SHA-1 to the SSL certification tab info?

I think it is unnecessary because the details of the signature are not important to most people.
