### ISSUE TITLE
非常容易实现的关于搜索的建议

### ISSUE THREAD

**Issue by xspgy** [tuyafeng/Via#941]
via浏览器主页的搜索框，输入有些带.的内容(android.app.Content,java.io.File)会把它当成网站，我建议主页搜索框只用来搜索文字，而不是访问链接，而主页上面那个搜索框主要用来访问网站，也可以搜索内容

**Comment by linlinzzo** [comment]
把点去掉就可以，有些用户习惯是改不了的。

**Comment by tuyafeng** [comment]
这个问题已经被解决了。
