### ISSUE TITLE
从其他APP中跳转打开链接时在后台打开？

### ISSUE THREAD

**Issue by Liquid-Aristocracy** [tuyafeng/Via#949]
从其他app中点击链接并用via打开时，如果via中本身有打开的tab，则会显示已有的tab，新链接在后台打开（打开后为非活动tab）。这样的设置是有意为之还是bug？在我使用中感到不方便（需要切换一下tab才能看到链接，并且为了查看链接关闭当前活动tab之后就会返回上一个app）

**Comment by tuyafeng** [comment]
我可以明确告诉你，是 bug😂😂。下个版本（4.3.2）修复。

**Comment by tuyafeng** [comment]
问题已修复。
