### ISSUE TITLE
「Form」应译为「表单」

### ISSUE THREAD

**Issue by Geeyun-JY3** [tuyafeng/Via#955]
对应字符串
https://github.com/tuyafeng/Via/blob/cbefea467d2c42b3e575dfe6e414f5f10cad47bf/app/src/main/res/values/strings.xml#L85
https://github.com/tuyafeng/Via/blob/cbefea467d2c42b3e575dfe6e414f5f10cad47bf/app/src/main/res/values-zh-rCN/strings.xml#L73
将「Form」译为「表单」是通用做法了。
「提交表格」是种怪怪的说法，而且不准确，「表格」和「表单」不是一类东西。

**Comment by tuyafeng** [comment]
感谢指正，确实应该用「表单」更合适，后续会修改。

**Comment by tuyafeng** [comment]
已修复 (349c329)。但应用版本应该是要等到 4.3.3 正式发布的时候了。
