### ISSUE TITLE
球球了！增添一个扫一扫的打开链接的功能吧！！！

### ISSUE THREAD

**Issue by git-stf-01** [tuyafeng/Via#959]
系统自带的浏览器我已经禁用了！！！简直不能忍！！！

还是Via好用。。用了好久了！！！！

**Comment by QJJXK555** [comment]
对，可以添加一个按钮，点击打开系统自带的扫一扫软件

**Comment by undefined303** [comment]
> 对，可以添加一个按钮，点击打开系统自带的扫一扫软件

理论上应该是可以调用各系统的扫一扫的（我已经看见实例了），但是不一定能保证所有系统都自带扫一扫，而且系统扫一扫出来的结果也不一定能被via获取

**Comment by Young-Lord** [comment]
安装一个同开发者的“二维码扫描”就行了

https://wwe.lanzoui.com/iFMYUwggvni
密码:hgke

**Comment by tuyafeng** [comment]
在 4.3.4 版本，二维码扫描插件内建到 Via 中了，此 issue 终结。
