### ISSUE TITLE
希望能增加智能拼页的功能

### ISSUE THREAD

**Issue by XjohnChen** [tuyafeng/Via#986]
网页看小说或者漫画时经常会有“下一页”，希望能自动加载，谢谢！

**Comment by aaaapai** [comment]
脚本了解？

**Comment by linlinzzo** [comment]
找到一些脚本，请自行下载。
[脚本地址](https://srvcn.xbext.com/mobile/share_scripts?filter=%E6%8B%BC%E9%A1%B5)

**Comment by XjohnChen** [comment]
谢谢！感谢关注和回复，希望浏览器能越做越好



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月30日 09:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [tuyafeng/Via] 希望能增加智能拼页的功能 (Issue #986) |

找到一些脚本，请自行下载。
脚本地址

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by linlinzzo** [comment]
问题解决了就关闭一下issue

**Comment by XjohnChen** [comment]
感谢回复
