### ISSUE TITLE
广告过滤已经一点用也没有了

### ISSUE THREAD

**Issue by twszgd** [tuyafeng/Via#994]
![Screenshot_20211223_165334](https://user-images.githubusercontent.com/93323725/147214795-6b8df149-23de-4e35-806f-4f6f6953cb93.jpg)
via浏览器广告过滤已经无效了很久了

**Comment by aaaapai** [comment]
不知道什么时候可以用扩展功能😢

**Comment by twszgd** [comment]
扩展功能必须要有第三方适配，手机浏览器目前没有第三方适配，所以应该不可能会有扩展功能。

**Comment by tuyafeng** [comment]
广告拦截是否有效，是以过滤器是否正常工作为判断依据，不以能否拦截搜索引擎广告作为判断依据。
